root-project/roottest

root/dataframe/CMakeLists.txt, root/dataframe/test_typeguessing.cxx, root/dataframe/test_typeguessing.ref
small test, only performs basic checks
=> [TDF] add test_typeguessing.cxx

root/dataframe/CMakeLists.txt, root/dataframe/test_par.cxx, root/dataframe/test_par.ref
compilation and execution times have been reduced
=> [TDF] reinstate test_par

root/dataframe/test_branchoverwrite.out, root/dataframe/test_functiontraits.cxx
This PR goes hand in hand with PR 575 for root, [here](https://github.com/root-project/root/pull/575).
=> [TDF] Deal with namespace changes of ROOT-8780

root/dataframe/regression_snapshot.C, root/dataframe/testIMT.cxx, root/dataframe/test_glob.C, root/dataframe/test_inference.cxx, root/dataframe/test_misc.cxx, root/dataframe/test_readerarray.cxx, root/dataframe/test_snapshot.C
Fixes tests broken by PR #703 in root.
=> [TDF] Change TH*F with TH*D and viceversa in tests

root/dataframe/regression_ranges.cxx
Lest the two tests concurrently write in the same file.
=> [TDF] Use a different file in regression_ranges and test_ranges

root/dataframe/CMakeLists.txt, root/dataframe/test_templateRecursionLimit.C
Cherry-pick conflicts:
root/dataframe/CMakeLists.txt
=> [TDF] Add recursion limit test

root/dataframe/test_reduce.C
To be merged after PR 757 in root.
=> [TDF] Use nicer syntax in test_reduce

root/dataframe/test_missingBranches.eref
Fix reference after changes introduced by PR 775 in root-project/root
=> [TDF] Update test_missingBranches reference

root/dataframe/test_snapshotNFiles.C
...by compiling instead of jitting three Snapshot invocations.
=> [TDF] Speed up test_snapshotNFiles

root/multicore/tthrobj_ttreeview_regression.cpp
This PR fixes the build failure in the test introduced by PR 828 in root-project/root.
=> [IMT] Update tthrobj_ttreeview_regression after TTreeView API changes

root/dataframe/CMakeLists.txt
See [ROOT-8924](https://sft.its.cern.ch/jira/browse/ROOT-8924) for more information.
=> [TDF] Re-introduce regression_zeroentries

root/hist/unit/CMakeLists.txt, root/io/compression/MainEvent.cxx, root/io/compression/Makefile, root/io/filemerger/Makefile, root/io/filemerger/execTestMultiMerge.C, root/io/filemerger/execTestMultiMerge.ref, root/io/treeForeign/Makefile, root/io/treeForeign/testForeignDraw.ref, root/io/treeForeign/testForeignDrawLZ4.ref, root/multicore/CMakeLists.txt, root/tree/cache/CMakeLists.txt, root/tree/cache/autocacheLZ4.ref, root/tree/cache/execperfstattestLZ4.oref, root/tree/cache/multiTreeLZ4.ref, root/tree/cloning/exectrimLZ4.ref
@pcanal Filemerger test fail for fast math builds is not related to tests but to cling behavior, and it will be be fixed as soon as possible.
=> Backporting LZ4 related changes for tests for v6-08-00

root/io/filemerger/execTestMultiMerge.C
Missing some commits to be backported..
=> V6-10-00 fix filemerger test

root/io/filemerger/execTestMultiMerge.C
Updating tolerance due changes in default value of fTitleOffset for ROOT v6-08-00
=> Changes in tolerance for files in filemerger test

root/meta/MemberComments.ref
https://github.com/root-project/root/pull/1305
=> Update reference to take into account root PR1305

root/dataframe/test_reports.cxx, root/dataframe/test_reports.ref
This tests the bug reported in [ROOT-9117](https://sft.its.cern.ch/jira/browse/ROOT-9117).
=> [TDF] Add one more test case to test_report

root/dataframe/CMakeLists.txt, root/dataframe/test_snapshot_manytasks.cxx
This test was added to v6.10-patches but was never added to the master branch.
=> [TDF] Add testing of Snapshot with many tasks per worker thread

.gitignore, root/io/xml/Makefile, root/io/xml/XmlDir.ref, root/io/xml/runXmlDir.C
Will work only after apply of https://github.com/root-project/root/pull/1386
=> Provide testing of subdirectories in TXMLFile

root/tree/cache/CMakeLists.txt, root/tree/cache/autocache.ref, root/tree/cache/execTestMissCache.cxx, root/tree/cache/execTestMissCache.ref, root/tree/cache/multiTree.ref
This PR contains a simple test of the "miss cache" functionality in https://github.com/root-project/root/pull/240.
=> Test new "miss cache" functionality of TTreeCache

root/dataframe/test_inference.cxx
this relates to ROOT PR https://github.com/root-project/root/pull/1855
=> [TDF] Replace TResultProxy into TResultPtr

root/dataframe/CMakeLists.txt
At least until we are ready for debugging
=> [TDF][TO REVERT] Disable test_stringfiltercolumn

root/dataframe/CMakeLists.txt
This PR complements https://github.com/root-project/root/pull/1961 , which extracts TDF from TreePlayer into the new DataFrame library.
=> [TDF] Adapt to the new DataFrame library

root/dataframe/CMakeLists.txt
This reverts commit 08472dbe2af8b650d42241e580179885c4440ebd.
=> Revert "[TDF][TO REVERT] Disable test_stringfiltercolumn"

root/io/filemerger/execTestMultiMerge.C
=> Adjust file size tolerances to reflect improvements in LZ4 1.8.2

root/meta/ROOT-7181/CMakeLists.txt, root/tree/addresses/CMakeLists.txt, root/treeproxy/CMakeLists.txt
This will allow us to remove -Droofit=Off
=> Exclude some make tests for enabling roofit

root/dataframe/CMakeLists.txt
This relates to https://github.com/root-project/root/pull/2543
=> [RDF] Remove RDF tests if the platform is a 32 bits one

cling/array/CMakeLists.txt
Resolved by root-project/root#2762
=> [cxxmodules] Remove workaround in runarray1.

cling/template/CMakeLists.txt, root/meta/autoloading/NestedClasses/CMakeLists.txt
Preparing to add rt cxxmodules in PRs
=> Disabling NestedClasses and slaveDisct tests for rt cxxmodules

root/tree/reader/CMakeLists.txt, root/tree/reader/test_numberBranchesRead.C
Add test for [#2921](https://github.com/root-project/root/pull/2921) in root project.
=> [TTreeReader][ROOT-9757] Check number of branches read

root/meta/enumPayloadManipulation/CMakeLists.txt, root/meta/enumPayloadManipulation/checkEnumFwdDecl.py, root/meta/enumPayloadManipulation/myenum.h, root/meta/enumPayloadManipulation/selection_x.xml, root/meta/enumPayloadManipulation/selection_y.xml, root/meta/enumPayloadManipulation/x.h, root/meta/enumPayloadManipulation/y.h
Linked to https://github.com/root-project/root/pull/3033
=> [TCling][ROOT-9660] Do not fwd declare on library load enums Cling kows already

python/cpp/PyROOT_advancedtests.py, python/cpp/Template.C
Backport of https://github.com/root-project/roottest/pull/260
=> [ROOT-9836] Add test for templated function in a namespace (backport to 6.16)

python/JupyROOT/CMakeLists.txt
Related to https://github.com/root-project/root/pull/3204
=> Adapt doctest tests to reorganization in JupyROOT directory

python/cpp/PyROOT_advancedtests.py, python/cpp/Template.C
Extension of template tests for https://github.com/root-project/root/pull/3237
=> [ROOT-9789] [NOBUILDS] Add test for non-instantiated member function templates

root/meta/tclass/regression/CMakeLists.txt, root/roofitstats/CMakeLists.txt
Part of the ongoing campaign to turn the experimental PyROOT builds green.
=> [Exp PyROOT] Modify tests after cppyy update

python/cmdLineUtils/CMakeLists.txt
Test is now working after changes of https://github.com/root-project/root/pull/3351
=> [Exp PyROOT] Re-enable test, ROOT facade is there

CMakeLists.txt, root/io/filemerger/CMakeLists.txt
Missing commits for https://github.com/root-project/roottest/pull/313
=> Fix standalone rootest.git

root/meta/expressiveErrorMessages.ref
=> [DictGen][ROOT-8566] Add extra-includes to payload 

python/CMakeLists.txt, python/cpp/CMakeLists.txt, python/cpp/PyROOT_cpp11tests.py, python/cpp/PyROOT_cpptests.py, python/function/CMakeLists.txt
Related to:
https://github.com/root-project/root/pull/3832
=> [Exp PyROOT] Fixes for python-cpp tests

root/dataframe/CMakeLists.txt
This PR is related to the ROOT PR [here](https://github.com/root-project/root/pull/3957).
=> [RDF] Build test only if library has been built

root/meta/method/execInlined.cxx, root/meta/method/execInlined.ref
Related to :
https://github.com/root-project/root/pull/4098
=> [TCling] Add test for kIsInlined bit of extra properties

python/cpp/PyROOT_cpptests.py
Test for https://github.com/root-project/root/pull/4121
=> [PyROOT] Test lookup and type of enums (global, ns)

python/cpp/PyROOT_cpptests.py
Fix is already in cppyy master, will be incorporated in next update.
=> [Exp PyROOT] Wait for fix in enum value lookup in cppyy

cling/functionTemplate/cintrun.ref-cling, cling/functionTemplate/pythoncintrun.ref, python/cpp/PyROOT_advancedtests.py, python/regression/PyROOT_regressiontests.py
Test for:
https://github.com/root-project/root/pull/4185
=> [PyROOT][ROOT-10256] Test for fix of return value of templated function

python/cpp/PyROOT_cpptests.py
Backport of https://github.com/root-project/roottest/pull/358
=> Backport 6.18: Tests for improved enum support in PyROOT

root/io/json/Objects.ref, root/io/json/PolyMarker.ref, root/io/json/RootClasses.ref, root/io/json/STL.ref, root/io/json/STL1.ref, root/io/json/StreamerLoop.ref, root/io/json/test_classes.h, root/io/xml/PolyMarker.ref
Must be applied after merging:
https://github.com/root-project/root/pull/4182
=> [json/xml] changes after excluding TObject bits from I/O

python/cpp/PyROOT_cpptests.py
Test for:
https://github.com/root-project/root/pull/4246
=> [PyROOT] Add test for lookup of scoped enums

python/cpp/PyROOT_cpptests.py
Backport of https://github.com/root-project/roottest/pull/372
=> [PyROOT] Backport 6.18: Add test for lookup of scoped enums

python/cpp/CMakeLists.txt, python/cpp/PyROOT_advancedtests.py, python/cpp/PyROOT_cpptests.py, python/memory/MemTester.C, python/regression/PyROOT_regressiontests.py, python/ttree/CMakeLists.txt, python/ttree/PyROOT_ttreetests.py
Goes together with https://github.com/root-project/root/pull/4264
=> [Exp PyROOT] Test adaptation and fixes for Cppyy update

python/basic/CMakeLists.txt, python/basic/PyROOT_basictests.py, python/basic/PyROOT_datatypetest.py, python/basic/PyROOT_overloadtests.py, python/memory/PyROOT_memorytests.py, python/regression/CMakeLists.txt, python/regression/PyROOT_regressiontests.py, python/regression/ScottCppyy.C
This goes together with https://github.com/root-project/root/pull/4294
=> [Exp PyROOT] Fixes in tests for collections, memory management of arguments, plotOn

root/io/json/STL.ref, root/io/json/STL0.ref, root/io/json/STL1.ref, root/io/json/runArrayCompress.C, root/io/json/runBasicTypes.C, root/io/json/runObjects.C, root/io/json/runPolyMarker.C, root/io/json/runSTL.C, root/io/json/runSTL0.C, root/io/json/runSTL1.C, root/io/json/runStreamerLoop.C, root/io/json/runString.C, root/io/json/test_classes.h
Add testing for fix in https://github.com/root-project/root/pull/4290
=> [json] add testing of nested STL containers

python/JupyROOT/CMakeLists.txt
JupyROOT tests fixed thanks to commit c499f6a.
=> [Exp PyROOT] JupyROOT tests enabled

root/meta/rootcling-modules/module-dep-order/CMakeLists.txt
We should remove the artifacts after each run and not only when
running the configuration step.
=> [cxxmodules] Fix the incremental builds.

python/basic/PyROOT_datatypetest.py
Test for https://github.com/root-project/root/pull/4345
=> [PyROOT][ROOT-10222] Add test for non-ASCII strings

python/basic/DataTypes.C, python/basic/DataTypes.h, python/basic/PyROOT_datatypetest.py
Goes together with: https://github.com/root-project/root/pull/4365
=> [PyROOT] Test PyUnicode and Bytes converters

python/cpp/PyROOT_cpptests.py
Goes together with https://github.com/root-project/root/pull/4559
And should be merged at the same time, @Axel-Naumann
=> Backport 6.16: test better enum support in TCling and PyROOT

root/io/filemerger/CMakeLists.txt, root/tree/fastcloning/references/execCheckClusterRange_builtinzlib.ref, root/tree/fastcloning/references/execCheckClusterRange_zlib.ref
The increased documentation change the file size.
=> [tree] Adapt to change in TLeaf[Element]::fIsRange

python/basic/CMakeLists.txt, python/basic/PyROOT_datatypetest.py
Fixed by cherry pick from cppyy. Related ticket:
https://bitbucket.org/wlav/cppyy/issues/145
Goes together with https://github.com/root-project/root/pull/4590
=> [Exp PyROOT] Test fixes

python/cpp/PyROOT_cpptests.py
Goes together with https://github.com/root-project/root/pull/4592
=> Backport 6.14: test better enum support in TCling and PyROOT

root/multicore/ttree_read_imt.cpp
With the training, we have:
Read entry 0 with learning -> Load basket for [0,100[ (or ] ?)
Read entry 117, learning over -> Load basket for rest of cluster [0, 663[
Read up to 500
Read entry 0 ->
TTreeCache believe it still processing the cluster but is missing data
-> Re-read all of the baskets that cover [0, 100[ but do not cover [100,500[ **individually**
=> Train the cache to avoid 'rewind' at each iteration.

root/io/compression/MainEvent.cxx, root/io/compression/Makefile, root/io/filemerger/CMakeLists.txt
Opened as a replacement of https://github.com/root-project/roottest/pull/352
=> Add ZSTD to compression test

python/basic/PyROOT_datatypetest.py, python/cpp/PyROOT_cpptests.py
Goes together with https://github.com/root-project/root/pull/4661
=> [PyROOT] Test new compatibility additions

python/stl/PyROOT_stltests.py
See ROOT PR [here](https://github.com/root-project/root/pull/4718).
=> [ROOT-10491] Test iteration over vector<bool>

python/cpp/PyROOT_cpptests.py
Goes together with https://github.com/root-project/root/pull/4795
=> [Exp PyROOT] Fix integer overflow in 32 bits

python/pythonizations/PyROOT_pythonizationtest.py
Goes together with https://github.com/root-project/root/pull/4895
=> [PyROOT] Add test for GetBinErrorUp/Low in TH2 (using decl overloads)

root/core/CMakeLists.txt, root/core/base64.C, root/core/base64.ref
It is now used in TBufferJSON, THttpServer, webgui, therefore has to be
tested
=> Add simple base64 test

python/basic/PyROOT_datatypetest.py, python/pythonizations/PyROOT_smartptrtest.py, python/regression/PyROOT_regressiontests.py, python/regression/ScottCppyy.C, python/stl/PyROOT_stltests.py
This PR goes together with https://github.com/root-project/root/pull/4957
and it contains:
- Adaptation/addition of tests for cppyy update
- Addition of regression tests for bugs fixes in experimental PyROOT.
=> [Exp PyROOT] Adapt tests to cppyy update

root/tree/fastcloning/references/execCheckClusterRange.ref32, root/tree/fastcloning/references/execCheckClusterRange_builtinzlib.ref, root/tree/fastcloning/references/execCheckClusterRange_zlib.ref
see https://github.com/root-project/root/pull/5038
=> Update ref following change in TStreamerInfo numbering -ROOT-10552

python/regression/PyROOT_regressiontests.py
Goes together with https://github.com/root-project/root/pull/5077
=> [PyROOT][ROOT-9516] Test for cleaning of proxied objects returned by value

root/meta/CMakeLists.txt
It was fixed by root-project/root#5036
=> Reenable runMembersComment

root/io/prefetching/runPrefetchReading.C, root/tree/addresses/assert_tread.cxx, root/tree/addresses/converterIssues/execReader.cxx, root/tree/addresses/relations_read.C, root/tree/addresses/relations_write.C, root/tree/addresses/runmemleak.C
=> add more missing includes [skip-ci]

python/pythonizations/PyROOT_pythonizationtest.py
Goes together with https://github.com/root-project/root/pull/5165
=> [PyROOT][ROOT-10606] Add test for STL sequence iter of RooArgSet

root/tree/friend/execNonExistingFriend.ref
Fixes a test broken by https://github.com/root-project/root/pull/5182
=> [Tree] Update ref file: non-existing TTrees cannot be added as friends

root/tree/friend/execNonExistingFriend.ref
This complements the backport in root: https://github.com/root-project/root/pull/5239
=> [Tree]  Update ref file: non-existing TTrees cannot be added as friends

root/meta/CMakeLists.txt, root/tree/CMakeLists.txt, root/treeformula/sync/CMakeLists.txt
=> Add back excluded tests for C++ modules

python/JupyROOT/CMakeLists.txt, python/JupyROOT/tpython.ipynb
Goes together with https://github.com/root-project/root/pull/5334
=> [Exp PyROOT][ROOT-8011] Add test for TPython from a C++ notebook

python/cpp/PyROOT_cpptests.py, python/ttree/PyROOT_ttreetests.py
Goes together with:
https://github.com/root-project/root/pull/5373
=> [Exp PyROOT][ROOT-10681] Modify tests for AddressOf and addressof

python/cpp/PyROOT_cpptests.py, python/ttree/PyROOT_ttreetests.py
Goes together with https://github.com/root-project/root/pull/5429
=> [Exp PyROOT] Fix / extend AddressOf tests

python/regression/CMakeLists.txt, python/regression/PyROOT_regressiontests.py
Goes together with https://github.com/root-project/root/pull/5495
=> [Exp PyROOT][ROOT-9447] Adapt tests to new default for argument parsing

cmake/modules/SearchInstalledSoftwareRoottest.cmake
More info: https://github.com/google/googletest/releases/tag/release-1.10.0
=> Update gtest to latest version 1.10.0 (sync)

root/meta/rootcling-modules/module-dep-order/CMakeLists.txt
This is part of root-project/root#5613
=> Fix test after the reworded diagnostic.

python/cpp/PyROOT_advancedtests.py
Test for https://sft.its.cern.ch/jira/browse/ROOT-8801?jql=project%20%3D%20ROOT%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22)%20AND%20component%20%3D%20PyROOT
=> [Exp PyROOT] Add test for variadic templates

root/meta/autoloading/headerParsingOnDemand/FullheaderParsingOnDemand.h
Should fail now and should get fixed by https://github.com/root-project/root/pull/5639
=> Add test against ROOT-10777.

root/multicore/tp_process_imt.ref
We do not create empty tasks anymore.
=> Adapt reference file to upgrade in TTreeProcessorMT

python/pickle/PyROOT_readtests.py, python/pickle/PyROOT_writetests.py
=> [PyROOT] Add read/write test for RooDataSet.

CMakeLists.txt, python/CMakeLists.txt, python/basic/CMakeLists.txt, python/basic/PyROOT_basictests.py, python/basic/PyROOT_datatypetest.py, python/basic/PyROOT_overloadtests.py, python/cling/CMakeLists.txt, python/cpp/CMakeLists.txt, python/cpp/PyROOT_advancedtests.py, python/cpp/PyROOT_cpp11tests.py, python/cpp/PyROOT_cpptests.py, python/function/CMakeLists.txt, python/function/PyROOT_functiontests.py, python/memory/CMakeLists.txt, python/memory/PyROOT_memorytests.py, python/pickle/CMakeLists.txt, python/pickle/PyROOT_readtests.py, python/pickle/PyROOT_writetests.py, python/pythonizations/CMakeLists.txt, python/pythonizations/PyROOT_pythonizationtest.py, python/pythonizations/PyROOT_smartptrtest.py, python/regression/CMakeLists.txt, python/regression/PyROOT_regressiontests.py, python/stl/CMakeLists.txt, python/stl/PyROOT_stltests.py, python/ttree/CMakeLists.txt, python/ttree/PyROOT_ttreetests.py
... and to the creation of the pyroot_legacy flag
Goes together with https://github.com/root-project/root/pull/5772
=> [PyROOT][CMake] Adapt tests to removal of pyroot_experimental flag

python/regression/CMakeLists.txt, python/regression/PyROOT_regressiontests.py
goes with https://github.com/root-project/root/pull/5643
=> Change AddLinkedLibs with Load in regression-regression test

root/tree/branches/execGetBranch.ref
See ROOT-10942 .
This PR accompanies https://github.com/root-project/root/pull/6072
=> [Tree] Update test ref: RDF changed the logic that lists branches

root/tree/branches/execGetBranch.ref
=> [Tree] Update test ref: RDF changed the logic that lists branches (v6.22)

root/tree/branches/execGetBranch.ref
=> [Tree] Update test ref: RDF changed the logic that lists branches (v6.20)

root/meta/rootcling/classInLinkdef.h
This matches the changes in root-project/root#6095
=> Remove the redundant linkdef rule.

python/JupyROOT/CMakeLists.txt
To be in sync with ROOT >= 6.20
=> [CMake][PyROOT] Make JupyROOT notebook tests serial

root/roofitstats/vectorisedPDFs/CMakeLists.txt, root/roofitstats/vectorisedPDFs/testNestedPDFs.cxx
Waits for merge of root-project/root #6178.
=> [RF] Remove a WILLFAIL since ROOT-10987 is here.

root/rint/TabCom.eref, root/rint/TabCom.oref, root/rint/TabCom_input.txt
This change follows root-project/root#5847
=> Adjust reference file.

python/regression/PyROOT_regressiontests.py
Tests for https://github.com/root-project/root/pull/6185
=> [PyROOT][ROOT-10872] Add C++-Python inheritance regression tests

root/roofitstats/stabilityTests.cxx
The test requires Minuit2, and will be skipped if its not available.
=> [RF] Update a stability test, suppress warnings.

root/dataframe/readShip.C, root/tree/branches/execLeafFullName.cxx, root/tree/branches/execLeafFullName.ref
In particular testing that the trailing underscore is present in a collection's index-leaf
=> Add more testing of TLeaf::GetFullName.

python/cpp/PyROOT_cpptests.py, python/regression/PyROOT_regressiontests.py
Extracted from the following JIRA issues:
https://sft.its.cern.ch/jira/browse/ROOT-10872
https://sft.its.cern.ch/jira/browse/ROOT-11010
https://sft.its.cern.ch/jira/browse/ROOT-10789
https://sft.its.cern.ch/jira/browse/ROOT-10786
=> [PyROOT] Add more tests for using declarations and Python-C++ inheritance

python/regression/PyROOT_regressiontests.py
Test for https://github.com/root-project/root/pull/6434
=> [PyROOT][6376] Add test for multi-inheritance case

python/JupyROOT/nbdiff.py
Fixes https://github.com/root-project/root/issues/6356.
=> [JupyROOT][6356] Filter out conflicting lines in notebook after update to nbconvert v6

python/regression/PyROOT_regressiontests.py
Test for https://github.com/root-project/root/pull/6582
=> [PyROOT][6467] Add test for inheritance from TChain

python/regression/PyROOT_regressiontests.py
Test for https://github.com/root-project/root/issues/6578 on the Python side.
=> [PyROOT][6578] Add test for constructor with all default parameters

root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx, root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h
Change in RF test corresponding to adding of new batch interface.
=> [RF] Correct renamed namespace in RF tests.

root/meta/tclass/CMakeLists.txt, root/meta/tclass/datamemberload.C, root/meta/tclass/datamemberload.h, root/meta/tclass/datamemberloadLinkDef.h
See https://github.com/root-project/root/pull/6668
=> Add test for Issue 6666: broken state handling in TClass::GetListOfDataMembers

root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx, root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h, root/roofitstats/vectorisedPDFs/testGaussBinned.cxx
Petty name changes for compatibility with #6968.
=> [RF] Update names for RooFitCompute library compatibility.

python/regression/PyROOT_regressiontests.py
Test for https://github.com/root-project/root/pull/6994
=> [PyROOT][6345] Add test for fix in cross inheritance

python/regression/PyROOT_regressiontests.py
Tests for https://github.com/root-project/root/pull/7022
=> [PyROOT][6470] Tests for cross inheritance

root/multicore/executorTests.hxx, root/multicore/tExecutor.cxx
still feels hackish and should be moved to gtest together with threadExecutor and processExecutor
=> Improvements and fixes for the tExecutor test

python/stl/PyROOT_stltests.py
Tests for:
https://github.com/root-project/root/pull/7071
https://github.com/root-project/root/pull/7072
=> [PyROOT][ROOT-10830] std::string tests

python/basic/PyROOT_datatypetest.py, python/basic/PyROOT_overloadtests.py, python/cling/cppyy_backend_check.h, python/cling/runPyAPITestCppyy.C, python/cling/runPyClassTest.C, python/common.py, python/regression/exec_root_6023.py, root/meta/tclass/regression/execNormalizationInf.py
Backport of:
https://github.com/root-project/roottest/pull/586
https://github.com/root-project/roottest/pull/587
=> [PyROOT] 6.22 - Backport fixes for conda builds

python/regression/PyROOT_regressiontests.py
Test for https://github.com/root-project/root/pull/7209
=> [PyROOT][7179] Test reduction of range of mapping __getitem__ to __call

python/distrdf/CMakeLists.txt, python/distrdf/test_friend_trees.py, python/distrdf/test_headers/header1.hxx, python/distrdf/test_headers/headers_folder/header2.hxx, python/distrdf/test_headers/headers_folder/header3.hxx, python/distrdf/test_histo_write.py, python/distrdf/test_include_headers.py, python/distrdf/test_inv_mass.py, python/distrdf/test_reducer_merge.py, python/distrdf/test_shared_libraries/a.cpp, python/distrdf/test_shared_libraries/a.h, python/distrdf/test_shared_libraries/myclass.h
Tests for https://github.com/root-project/root/pull/7139
=> Introduce ROOT.RDF.Distributed

root/dataframe/test_branchoverwrite.cxx, root/dataframe/test_branchoverwrite.ref, root/dataframe/test_columnoverride.cxx
Companion PR for https://github.com/root-project/root/pull/7333
=> [DF] Improvements to CheckDefine

cling/dict/fwd-decl-enumconstant/CMakeLists.txt, cling/dict/fwd-decl-enumconstant/Hash.h, cling/dict/fwd-decl-enumconstant/HashedTypes.h, cling/dict/fwd-decl-enumconstant/ParameterSetID.h, cling/dict/fwd-decl-enumconstant/classes.h, cling/dict/fwd-decl-enumconstant/execfwdDeclEnumconstant.C, cling/dict/fwd-decl-enumconstant/selection.xml
See https://github.com/cms-sw/cmsdist/pull/6690#issuecomment-788782759
Tests https://github.com/root-project/root/issues/7390
=> Add test for CMS fwd decl enumerator as template arg:

python/distrdf/CMakeLists.txt
Adding https://github.com/root-project/roottest/pull/671 to master as well
=> Use new pyspark build option to activate tests

python/distrdf/CMakeLists.txt
Sibling PR to https://github.com/root-project/root/pull/7413
=> Build option for distributed RDF tests that use pyspark

root/dataframe/test_branchoverwrite.ref
Companion PR for https://github.com/root-project/root/pull/7384
=> [DF] Update test ref after change in error message

scripts/Rules.mk
See https://github.com/root-project/root/pull/7635
=> [skip-ci] More macOS 11 fixes.

root/io/filemerger/CMakeLists.txt, root/io/filemerger/execKeyOrder.C, root/io/filemerger/execKeyOrder.ref
See commit a161aa4e722d87e1bb9316177388046f45837e24 Fix hist headers Doxygen syntax (#7726).
=> Adapt to change in histogram doc string.

python/pickle/PyROOT_readtests.py
Sibling PR to https://github.com/root-project/root/pull/7886
=> Test serialization of the ROOT facade

python/basic/PyROOT_datatypetest.py
Tests for https://github.com/root-project/root/pull/8036
=> [PyROOT][7501] Add test for setting of array data members

CMakeLists.txt, cling/exception/CMakeLists.txt, root/dataframe/CMakeLists.txt
master version of https://github.com/root-project/roottest/pull/702
=>  Some more Apple M1 roottest fixes

python/ttree/PyROOT_ttreetests.py
Test for https://github.com/root-project/root/pull/8282
=> [PyROOT][8183] Add test for TTreeReader iteration

root/dataframe/CMakeLists.txt, root/dataframe/test_snapshot_copyaddresses.C
This is the same as PR #710 but now from a branch that has the same name as the branch in root.git that fixes the test.
=> [DF] Test Snapshot of members of TBranchElement from many input files

python/pickle/PyROOT_readtests.py, python/pickle/derived.py
Test for https://github.com/root-project/root/pull/8476
=> [PyROOT] Add test for cross-inheritance object pickling

python/distrdf/test_friend_trees.py
Sibling PR of https://github.com/root-project/root/pull/8605
Tests against reproducer of root-project/root#7584
=> [DF] Test against reproducer of #7584

python/distrdf/test_reducer_merge.py
Sibling PR of https://github.com/root-project/root/pull/8623
=> [DF] Adapt test to naming scheme of distributed snapshot

cmake/modules/RoottestMacros.cmake
This PR is related to https://github.com/root-project/root/issues/8707
https://github.com/root-project/root/pull/8722/ has to be merged first as the arguments are forwarded to `ROOT_ADD_TEST`
`ROOTTEST_ADD_TEST` and `ROOTTEST_GENERATE_EXECUTABLE` now take `FIXTURES_SETUP`, `FIXTURES_CLEANUP` and `FIXTURES_REQUIRED` arugments (lists)
also add a `RESOURCE_LOCK` to prevent parallel execution of a test that
takes a single lock name
n.b: fixtures and resource lock namespace are each different from test
namespaces
=> add fixture support to ROOTTEST_ADD_TEST and ROOTTEST_GENERATE_EXECUTABLE

python/distrdf/test_reducer_merge.py
The getter is an implementation detail anyway.
=> [DF] Call attribute rather than getter

python/distrdf/test_friend_trees.py, python/distrdf/test_histo_write.py, python/distrdf/test_include_headers.py, python/distrdf/test_inv_mass.py, python/distrdf/test_reducer_merge.py
Sibling PR to https://github.com/root-project/root/pull/8938
=> [DF] Suppress spurious ResourceWarning in distrdf-pyspark tests

python/distrdf/CMakeLists.txt, python/distrdf/test_definepersample.py
Sibling PR in ROOT https://github.com/root-project/root/pull/9074
=> [DF] Add DefinePerSample tests in DistRDF

python/distrdf/common/CMakeLists.txt, python/distrdf/common/test_rungraphs.py, python/distrdf/dask/CMakeLists.txt, python/distrdf/dask/test_rungraphs.py, python/distrdf/spark/CMakeLists.txt, python/distrdf/spark/test_rungraphs.py
Sibling PR to root-project/root#9344
=> [DF] Test distributed RunGraphs

python/distrdf/common/test_rungraphs.py, python/distrdf/dask/test_backend.py, python/distrdf/dask/test_definepersample.py, python/distrdf/dask/test_friend_trees.py, python/distrdf/dask/test_histo_write.py, python/distrdf/dask/test_include_headers.py, python/distrdf/dask/test_inv_mass.py, python/distrdf/dask/test_reducer_merge.py, python/distrdf/dask/test_rungraphs.py
This is good custom in general and it might also help with sporadic failures on mac nodes
=> [DF] Make sure to close the Dask client as well

root/meta/MemberComments.ref
This PR https://github.com/root-project/root/pull/9472 has changed the signature of DrawArrow
=> New signature for DrawArrow

root/meta/MemberComments_win32.ref
The ref file for win32 should be also updated.
=> update the ref file for win32

cling/specialobj/f02.ref
Needed for https://github.com/root-project/root/pull/9537
=> Update ref file to reflect removed "." in msg.

python/distrdf/dask/test_reducer_merge.py, python/distrdf/spark/test_reducer_merge.py
Sibling PR to https://github.com/root-project/root/pull/9658
=> [DF] Add test for Redefine in distributed RDataFrame

python/distrdf/dask/test_reducer_merge.py, python/distrdf/spark/test_reducer_merge.py
Sibling PR to https://github.com/root-project/root/pull/9668
=> [DF][6.26] Add test for Redefine in distributed RDataFrame

cling/exception/CMakeLists.txt
roottest part of https://github.com/root-project/root/pull/9548
=> Pass `--ptrcheck` to ptrcheck test.

root/dataframe/test_ROOT9975.C
Fixes a test failure in https://github.com/root-project/root/pull/9699
=> [DF] Remove dependency from exact column ordering from a test

cling/function/CMakeLists.txt, cling/function/trybody.C, cling/function/trybody.ref
See https://github.com/root-project/root/issues/9664 for context.
=> [cling] Add test for function with try-catch body

cling/exception/CMakeLists.txt
roottest part of https://github.com/root-project/root/pull/9704
=> Pass `--ptrcheck` to ptrcheck test. (6-26)

cling/function/CMakeLists.txt
See https://github.com/root-project/root/issues/7541
=> Disable new Cling test with exception on M1

root/tree/evolution/split/Makefile, root/tree/evolution/split/execCreateFileFullObjRule.cxx, root/tree/evolution/split/execCreateFileFullObjRule.ref, root/tree/evolution/split/execReadFileFullObjRule.cxx, root/tree/evolution/split/execReadFileFullObjRule.ref
See https://github.com/root-project/root/pull/8429
=> Add test for issue 8428 (scheduling of full object rules in tree)

python/distrdf/common/CMakeLists.txt, python/distrdf/common/test_rungraphs.py, python/distrdf/dask/test_rungraphs.py, python/distrdf/spark/CMakeLists.txt, python/distrdf/spark/test_backend.py, python/distrdf/spark/test_definepersample.py, python/distrdf/spark/test_friend_trees.py, python/distrdf/spark/test_histo_write.py, python/distrdf/spark/test_include_headers.py, python/distrdf/spark/test_inv_mass.py, python/distrdf/spark/test_reducer_merge.py, python/distrdf/spark/test_rungraphs.py
=> Backport fixes to distrdf tests in 6.26

python/distrdf/dask/test_reducer_merge.py, python/distrdf/spark/test_reducer_merge.py
Sibling PR to https://github.com/root-project/root/pull/9854
=> [DF] Add test for distributed HistoND

python/distrdf/dask/test_reducer_merge.py, python/distrdf/spark/test_reducer_merge.py
Backport of https://github.com/root-project/roottest/pull/823
=> [6.26] Add test for distributed HistoND

root/io/datamodelevolution/00/test2.cxx, root/io/datamodelevolution/00/test2.ref, root/io/issue-9899/CMakeLists.txt, root/io/issue-9899/read_cmssw_class_v3.cxx, root/io/issue-9899/read_cmssw_class_v3.ref, root/io/issue-9899/write_cmssw_class_v2.cxx, root/io/issue-9899/write_cmssw_class_v2.ref
[See #9913](https://github.com/root-project/root/pull/9913)
=> Add test for issue9899 (rules for missing/new data members)

root/roofitstats/read_scientific_notation.ref
This needs to be merged together with https://github.com/root-project/root/pull/9965.
=> [RF] Remove RooFit banner from reference files

python/distrdf/dask/test_reducer_merge.py, python/distrdf/spark/test_reducer_merge.py
Sibling PR of https://github.com/root-project/root/pull/9995
=> [DF] Test lazy instant actions in distributed mode

python/distrdf/dask/test_reducer_merge.py, python/distrdf/spark/test_reducer_merge.py
Backport of #836 . Sibling PR to https://github.com/root-project/root/pull/10027
=> [6.26] Test lazy instant actions in distributed mode

python/distrdf/dask/CMakeLists.txt, python/distrdf/dask/test_variations.py, python/distrdf/spark/CMakeLists.txt, python/distrdf/spark/test_variations.py
Sibling PR to https://github.com/root-project/root/pull/9942
=> Add tests for systematic variations in distributed RDataFrame

cmake/modules/RoottestMacros.cmake
Sibling of https://github.com/root-project/root/pull/10194
=> [cmake] Enable passing PROPERTIES in ROOTTEST_ADD_TEST

python/distrdf/dask/check_friend_trees.py, python/distrdf/spark/check_friend_trees.py
Sibling PR of https://github.com/root-project/root/pull/10244
=> [DF] Add distributed test with main TTree and friend TTree

python/distrdf/dask/check_reducer_merge.py, python/distrdf/spark/check_reducer_merge.py
Attempt to fix some errors seen in CI like https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/140477/testReport/projectroot.roottest.python.distrdf/dask/roottest_python_distrdf_dask_test_all/
=> [DF] Make file names in snapshot test more unique

python/distrdf/dask/check_reducer_merge.py, python/distrdf/spark/check_reducer_merge.py
Backport of #855 . Backporting because it helps in stabilizing CI
=> [6.26][DF] Make file names in snapshot test more unique

root/dataframe/test_snapshot.ref
Some changes in Snapshot affect the order of the output.
=> [DF] Update test reference

root/dataframe/test_snapshot.ref
Some changes in Snapshot affect the order of the output.
=> [DF] Update test reference (v6.26)

python/distrdf/dask/check_backend.py, python/distrdf/spark/check_backend.py
Sibling of https://github.com/root-project/root/pull/10098
=> [DF] Change distributed tests following new logic for building ranges

scripts/custom_diff.py
This PR will be used to investigate 32 bits failures (and get readable diffs out of it).
=> Don't ignore white space in diffs

root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h, root/roofitstats/vectorisedPDFs/testGaussBinned.cxx
This should be merged with https://github.com/root-project/root/pull/10803.
=> [RF] Avoid using RunContext in roottest

python/distrdf/dask/check_backend.py, python/distrdf/dask/check_friend_trees.py, python/distrdf/dask/check_include_headers.py, python/distrdf/dask/check_reducer_merge.py, python/distrdf/dask/check_variations.py, python/distrdf/spark/check_backend.py, python/distrdf/spark/check_friend_trees.py, python/distrdf/spark/check_include_headers.py, python/distrdf/spark/check_reducer_merge.py, python/distrdf/spark/check_variations.py
Sibling PR of https://github.com/root-project/root/pull/10368
=> [DF] Add histogram models in distributed tests

root/tree/entrylist/CMakeLists.txt, root/tree/entrylist/regression_intoverflow.cxx
=> [6.26][tree] Test TEntryList::GetEntryAndTree with index larger than max int

python/distrdf/dask/check_friend_trees_alignment.py, python/distrdf/dask/test_all.py, python/distrdf/spark/check_friend_trees_alignment.py, python/distrdf/spark/test_all.py
Sibling PR of https://github.com/root-project/root/pull/10939
=> [DF] Add test for friend alignment

python/distrdf/dask/check_friend_trees_alignment.py, python/distrdf/dask/test_all.py, python/distrdf/spark/check_friend_trees_alignment.py, python/distrdf/spark/test_all.py
=> [6.26][DF] Add test for friend alignment

root/roofitstats/vectorisedPDFs/testNestedPDFs.cxx
Related to https://github.com/root-project/root/pull/11162.
=> [RF] Update `testNestedPDFs` to avoid integrating a RooRealVar

.gitignore, root/meta/MemberComments.ref, root/meta/MemberComments_win32.ref
Should fix changes after https://github.com/root-project/root/pull/10915
=> Fix MemberComments test after modify TH1.h header

root/meta/MemberComments.ref, root/meta/MemberComments_win32.ref
Will be changed after https://github.com/root-project/root/pull/11350
=> Fix MemberComments tests

python/JupyROOT/nbdiff.py, python/regression/PyROOT_regressiontests.py
see https://github.com/root-project/root/pull/11621
=> [skip-ci] Tweaks for AddressSanitizer

root/meta/MemberComments.ref, root/meta/MemberComments_win32.ref
This PR https://github.com/root-project/root/pull/11645 adds a method in TArrow. which
makes some ref files invalid.
=> A change in TArrow requires ref files update.

root/meta/execTypedefList.C, root/meta/typelist.v5.txt, root/meta/typelist_win32.v5.txt
Pairs up with https://github.com/root-project/root/pull/12355.
=> [math] Remove non-existing typedefs from reference files

root/meta/execTypedefList.C, root/meta/naming/execClassEditNormalize.C, root/meta/tclass/runpairs.C, root/meta/typelist.v6.txt, root/tree/cache/assertTooSmall.C
The common cause for the remaining failure after these fixes is https://github.com/root-project/root/issues/12747
=> Fixes for C++20

root/meta/execTypedefList.C, root/meta/typelist.v6.txt, root/roofitstats/vectorisedPDFs/testLognormal.cxx
Backport of https://github.com/root-project/roottest/pull/962; goes together with https://github.com/root-project/root/pull/12899
=> Test fixes for mac13(arm) [v6.28]

cmake/modules/RoottestMacros.cmake, root/io/event/CMakeLists.txt, scripts/CMakeLists.txt
this makes yet another batch of tests pass on FreeBSD
=> [FreeBSD] Be explicit that gmake is required

root/dataframe/test_progressiveCSV.sh
found one more instance of a test failing
=> Use /bin/sh instead of bash

root/dataframe/.rootrc
for https://github.com/root-project/root/pull/13460
=> [skip-ci] dataframe: Disable ACLiC rootmap generation on Windows

root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
Change the code so that it compiles also after merging the following PR in `root`:
https://github.com/root-project/root/pull/13389
=> [RF] Adapt to changes in BatchMode

root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
Goes together with https://github.com/root-project/root/pull/13530.
=> [RF] Adapt roottest to new `RooFit::Evaluator`

python/distrdf/dask/check_reducer_merge.py, python/distrdf/spark/check_reducer_merge.py
Tests for the GraphAymmErrors operation for the Dask and Spark backends with DistRDF.
=> Tests for DistRDF GraphAymmErrors

boost/functional.hpp, root/meta/naming/cmsExample01.h
for which the templates are defined in the std library.
=> Fix unary/binary function also for older sdks

python/regression/PyROOT_regressiontests.py
in presence of an overloaded operator
=> [Backport][Cppyy][13410] Test accessibility of derived class

root/io/TFile/execStreamerInfoHash.cxx, root/io/TFile/execStreamerInfoHash.ref
See [#12783](https://github.com/root-project/root/issues/12783)
=> Add test for ROOT's # 12783 (Incorrect caching of StreamerInfo record)

python/distrdf/CMakeLists.txt, python/distrdf/dask/check_backend.py
This reverts commit 3971a5488667a8d1a5d7a52228bc56cfe735ef2f.
Closes https://github.com/root-project/root/issues/10061
=> Revert "[DF] Disable distributed tests on M1 ARM"

root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
Sibling of https://github.com/root-project/root/pull/14187
=> [RF] Adapt to change in header

python/regression/PyROOT_regressiontests.py
Never run because of `--fixcling` command line argument.
=> Resurrect PyROOT regression tests

python/JsMVA/EnableJsMVA.ipynb, python/JsMVA/NewMethods.ipynb, python/JsMVA/UserInterface.ipynb, python/JsMVA/nbdiff.py, python/JupyROOT/importROOT.ipynb, python/JupyROOT/nbdiff.py, python/JupyROOT/simpleCppMagic.ipynb
Sister PR of https://github.com/root-project/root/pull/14661
=> [PyROOT] Adapt to the removal of the welcome message in JupyROOT

root/meta/genreflex/ROOT-5768/CMakeLists.txt, root/meta/genreflex/ROOT-5768/CoolKernel/pointers.h, root/meta/genreflex/ROOT-5768/Makefile, root/meta/genreflex/ROOT-5768/PyCool.h, root/meta/genreflex/ROOT-5768/PyCool_selection.xml
=> [meta] Add back the ROOT-5768 test

root/collection/execTClonesArrayAbsorb.C, root/hist/profile/runcopy.C, root/io/TFile/execFlipOver.C, root/io/directory/execOverWriteDir.C, root/meta/ROOT-7181/scripts/case1.script, root/tree/addresses/runaugertest.C, root/tree/addresses/suetestwrt.C, root/tree/branches/execbref.C, root/tree/cache/runcachedchain.C, root/tree/chain/execfilenameformats.C, root/tree/chain/execresetbranch.C, root/tree/entrylist/runchain.C, root/tree/friend/runchainBranchStatus.C, root/tree/selector/runSelectorCintTest.C, root/treeformula/array/indexMultiDim.C, root/treeformula/parse/runexpotest.C, root/treeformula/retobj/runretobjTest.C, root/treeformula/schemaEvolution/schemaRun3.C, root/treeformula/schemaEvolution/schemaRun3a.C, root/treeformula/string/createAliasStringMakeProxy.C, root/treeformula/string/execAliasString.C, root/treeproxy/stlvec/createtlorentzvecproxy.C, root/treeproxy/stlvec/runtlorentzvec.C, scripts/FixCling.mk
This is related to: https://github.com/root-project/root/pull/14645
The failing checks in the above PR are due to warnings added interfering with the test outputs.
=> Add 'auto' keyword to variable declarations

root/meta/ROOT-7181/scripts/case2.script, root/meta/ROOT-7181/scripts/case3.script
Missed 2 more instances of `auto` keyword in this PR: https://github.com/root-project/roottest/pull/1056
=> Add `auto` keyword to variable declarations: more instances

root/meta/runnamespace.C
Fixes https://github.com/orgs/root-project/projects/8/views/1?pane=issue&itemId=52382006
=> [meta] Remove cling workaround with runtime check for modules

root/io/evolution/versions/attmarker.ref, root/io/hadd/CMakeLists.txt, root/io/hadd/test_compression_settings.py, root/io/newstl/emulatedWrite.ref, root/io/transient/base/hadd_autoloadZLIB.ref
Tests for the compression algorithm setting in `hadd`.
=> [io] Add tests for hadd compression settings

python/basic/CMakeLists.txt, python/cling/CMakeLists.txt, python/regression/CMakeLists.txt, root/meta/tclass/regression/CMakeLists.txt
This goes together with the corresponding ROOT PR:
https://github.com/root-project/root/pull/14703
=> [PyROOT] Revert patch for versioned PyROOT libraries

python/cpp/PyROOT_cpp11tests.py
See https://github.com/root-project/root/issues/14232.
=> [PyROOT] New unit test with reproducer from ROOT issue 14232

root/treeformula/schemaEvolution/Makefile
BP of https://github.com/root-project/roottest/pull/967
=> [Backport] Adapt to better resetting of fBits at read time

python/JupyROOT/nbdiff.py
=> [PR] Make the nbdiff utility compatible with all nbconvert versions

python/JupyROOT/nbdiff.py
fixes #14303
BP of https://github.com/root-project/roottest/pull/1082
=> [PR] 6.26 Make the nbdiff utility compatible with all nbconvert versions

python/JupyROOT/nbdiff.py
fixes #14303
BP of https://github.com/root-project/roottest/pull/1082
=> [BP] Make the nbdiff utility compatible with all nbconvert versions

root/graf/CMakeLists.txt, root/graf/tasimage_frompad.C
=> [graph] Test vmemory usage of TASimage::FromPad

python/cpp/PyROOT_cpp11tests.py, python/regression/PyROOT_regressiontests.py, python/ttree/PyROOT_ttreetests.py
Sister PR of https://github.com/root-project/root/pull/14507.
=> [PyROOT] Update cppyy to a recent version

python/regression/PyROOT_regressiontests.py
Sister PR of https://github.com/root-project/root/pull/15125.
=> [PyROOT] Add unit test to cover ROOT issue 15117

root/tree/cache/execLastCluster.C, root/tree/cache/execLastCluster.ref
matches https://github.com/root-project/root/pull/14818
=> adapt cachesize after clamping

root/io/filemerger/CMakeLists.txt, root/io/treeForeign/testForeignDrawZLIB.ref, root/io/treeForeign/testForeignDrawZLIB_builtinzlib.ref, root/io/xml/PolyMarker.ref, root/tree/cloning/references/exectrimZLIB.ref, root/tree/cloning/references/exectrimZLIB_builtinzlib.ref, root/tree/cloning/references/exectrimZLIB_i686_win32.ref, root/tree/fastcloning/references/execCheckClusterRange.ref32, root/tree/fastcloning/references/execCheckClusterRange_builtinzlib.ref, root/tree/fastcloning/references/execCheckClusterRange_zlib.ref, root/tree/fastcloning/references/execCheckClusterRange_zlib_win64.ref
matches https://github.com/root-project/root/pull/15021
=> update tests with new classdef tattmarker version

root/meta/MemberComments.ref, root/meta/countIncludePaths.C, root/tree/branches/execGetBranch.cxx
This is related/need by https://github.com/root-project/root/pull/14792
=> MemberComments: add missing/new operator delete(void *, size_t)

root/meta/tclass/execProperties.C
See https://github.com/root-project/root/pull/15113
=> Adjust to removal of TClass::kHasCustomStreamerMember

root/io/hadd/CMakeLists.txt, root/io/hadd/input_validation.py
sibling of https://github.com/root-project/root/pull/16001
=> [skip-ci] Add test for hadd input format validation

root/io/hadd/CMakeLists.txt, root/io/hadd/input_validation.py
Backport of:
* https://github.com/root-project/roottest/pull/1142
=> [io] Add test for hadd input data format validation

root/io/hadd/CMakeLists.txt, root/io/hadd/hadd_check_comp_tree.C, root/io/hadd/hadd_gen_input_tree.C
see https://github.com/root-project/root/pull/16082
=> [hadd] add test for hadd compression algorithm change for TTree

root/io/evolution/versions/attmarker.ref, root/io/filemerger/CMakeLists.txt
See https://github.com/root-project/root/pull/16082
=> [io] update test expectations for hadd after #16082

root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
this PR resolves https://github.com/root-project/root/issues/16182
=> added missing include

root/tree/reader/CMakeLists.txt, root/tree/reader/runcleanupChain.C
This code has been written by David Smith and minimally edited for its integration in roottest.
This PR is picked up by this PR to the ROOT repo https://github.com/root-project/root/pull/16198
=> [TTreeReader] Properly cleanup non-owned chains (Test for it)

root/tree/branches/CMakeLists.txt, root/tree/branches/initOffset.C
Fixes ROOT-5983
Test tested by https://github.com/root-project/root/pull/16213
=> [tree] Add test for PR #7119

root/rint/CMakeLists.txt
test for ROOT-5843 (see ROOT PR https://github.com/root-project/root/pull/16301 )
=> Test for the .libraries command for the prompt

root/collection/AccidentalOwnership.C
Corresponding PR in root https://github.com/root-project/root/pull/16435
=> [Core] Add test for ROOT-7137

root/io/uniquePointer/checkNameForIO.C
See https://github.com/root-project/root/pull/16495
=> Adapt to TClassEdit::GetNameForIO returning the trailing star

root/aclic/misc/CMakeLists.txt, root/aclic/misc/addIncludePath.C, root/aclic/misc/addIncludePathGCCMajor.C, root/aclic/misc/addIncludePathTest.C
and therefore fixing the ticket as per comment on the item: see https://its.cern.ch/jira/browse/ROOT-8991
=> Add test for ROOT-8991

root/io/hadd/CMakeLists.txt, root/io/hadd/hadd_check_nested_same_name.C, root/io/hadd/hadd_check_nested_same_name.ref
Depends on https://github.com/root-project/root/pull/16518
=> Add regression test for #16190

root/rint/CMakeLists.txt, root/rint/main.cpp
See the sister PR https://github.com/root-project/root/pull/16766
=> Add test for #11707

root/meta/MemberComments.ref, root/meta/MemberComments_win32.ref, root/meta/MemberComments_win64.ref
sibling of https://github.com/root-project/root/pull/16697
=> adapt to new context menu function in th1

python/numba/PyROOT_numbatests.py
So far, the test was only skipped if the numba version was too low, but it might also happen that numba is not installed at all. For example if one uses Python 3.13, which doesn't support numba yet.
=> [PyROOT] Skip numba test also if numba is not available at all

python/numba/PyROOT_numbatests.py
So far, the test was only skipped if the numba version was too low, but it might also happen that numba is not installed at all. For example if one uses Python 3.13, which doesn't support numba yet.
=> [v634][PyROOT] Skip numba test also if numba is not available

root/meta/MemberComments.ref, root/meta/MemberComments_win32.ref, root/meta/MemberComments_win64.ref
sibling of https://github.com/root-project/root/pull/16920
=> remove complex-arg context menu functions

root/io/hadd/merge_gen_input_tuples.C, root/ntuple/basics.C
Companion PR to https://github.com/root-project/root/pull/17025
=> [ntuple] adapt to MakeField API changes

root/multicore/tProcessExecutorH1Test.cpp
Fixes failure caused by https://github.com/root-project/root/pull/17097
```
2462:roottest-root-multicore-processExecutorH1Test
```
=> Fix path in multicore tutorials

python/distrdf/backends/check_reducer_merge.py
from @vepadulano, to test https://github.com/root-project/root/pull/17171
=> Add test for distributed Alias

.gitignore, root/io/newstl/TestHelpers.C, root/meta/evolution/mixedBase_merge1.ref
Backport of https://github.com/root-project/roottest/pull/1224
Companion to
=> [v634] Adapt to change in error case behavior.

root/io/TFile/execFlipOver.C, root/meta/namespace.ref, root/meta/namespace.ref32
Companion to https://github.com/root-project/root/pull/17236
=> [io] Adjust test to new, empty default title

root/meta/evolution/mixedBase_merge1.ref
Companion to https://github.com/root-project/root/pull/17272
=> Revert "Adapt to change in error case behavior."

root/io/hadd/merge_gen_input_tuples.C, root/ntuple/basics.C
Companion PR to https://github.com/root-project/root/pull/17297
=> [ntuple] remove pre-release warning workaround

root/io/hadd/merge_changeComp_check_output.C
Companion PR to https://github.com/root-project/root/pull/17389
=> [ntuple] fix-up for fCompressionSettings being an optional

root/io/evolution/ioReadRuleEquivalentCode_selection.xml, root/io/evolution/issue-8083/Makefile
The companion ROOT PR is https://github.com/root-project/root/pull/17549
=> Add missing dependency in rootttest-root-io-evolution

root/io/hadd/hadd_check_cms.C
Companion of https://github.com/root-project/root/pull/17665
=> [ntuple] adjust to interface changes

root/io/evolution/rules/execSourceTypes.cxx, root/io/evolution/rules/execSourceTypes.ref
This is the companion PR of https://github.com/root-project/root/pull/17604
and testing the issue seen at https://github.com/cms-sw/cmsdist/pull/9643#issuecomment-2632063998
=> io: add rule test with std::string input

root/io/hadd/CMakeLists.txt, root/io/hadd/hadd_check_filtered.C, root/io/hadd/hadd_filter.txt, root/io/hadd/hadd_gen_input_files.C
Companion of  https://github.com/root-project/root/pull/17612
=> [hadd] add tests for -L/-Ltype flags

root/io/hadd/merge_changeComp_check_output.C
Companion of https://github.com/root-project/root/pull/17878
=> [hadd] use GetCompressionSettings() instead of fCompressionSettings

cling/CMakeLists.txt, root/dataframe/testIMT.cxx, root/dataframe/test_misc.cxx, root/dataframe/test_read_leaves.cxx, root/dataframe/test_read_leaves_nodict.cxx, root/io/cpp11Containers/commonUtils.h, root/multicore/CMakeLists.txt
Companion of https://github.com/root-project/root/pull/15853
=> Fix some test warnings

python/distrdf/backends/check_inv_mass.py, root/multicore/tProcessExecutorH1Test.cpp, root/multicore/ttree_read_imt.cpp, root/multicore/ttree_read_imt.sh, root/multicore/ttree_read_imt_allpar.cpp, root/multicore/ttree_read_imt_allpar.sh, root/tree/reader/assertIntroTut.C, root/tree/reader/execIntroTut.C
preferring local generation of test files or EOS via xrootd
Companion PR to run the tests https://github.com/root-project/root/pull/18041
=> Remove unnecessary http accesses

python/distrdf/dask/check_inv_mass.py, root/multicore/tProcessExecutorH1Test.cpp, root/multicore/ttree_read_imt.cpp, root/multicore/ttree_read_imt.sh, root/multicore/ttree_read_imt_allpar.cpp, root/multicore/ttree_read_imt_allpar.sh, root/tree/reader/assertIntroTut.C, root/tree/reader/execIntroTut.C
preferring local generation of test files or EOS via xrootd
BP of https://github.com/root-project/roottest/pull/1283
Companion PR https://github.com/root-project/root/pull/18051
=> [BP][6.30] Remove unnecessary http accesses

python/distrdf/backends/check_inv_mass.py, root/multicore/tProcessExecutorH1Test.cpp, root/multicore/ttree_read_imt.cpp, root/multicore/ttree_read_imt.sh, root/multicore/ttree_read_imt_allpar.cpp, root/multicore/ttree_read_imt_allpar.sh, root/tree/reader/assertIntroTut.C, root/tree/reader/execIntroTut.C
preferring local generation of test files or EOS via xrootd
BP of https://github.com/root-project/roottest/pull/1283
Companion PR https://github.com/root-project/root/pull/18052
=> [BP][6.32] Remove unnecessary http accesses

python/distrdf/backends/check_inv_mass.py, root/multicore/tProcessExecutorH1Test.cpp, root/multicore/ttree_read_imt.cpp, root/multicore/ttree_read_imt.sh, root/multicore/ttree_read_imt_allpar.cpp, root/multicore/ttree_read_imt_allpar.sh, root/tree/reader/assertIntroTut.C, root/tree/reader/execIntroTut.C
preferring local generation of test files or EOS via xrootd
BP of https://github.com/root-project/roottest/pull/1283
Companion PR https://github.com/root-project/root/pull/18053
=> [BP][6.34] Remove unnecessary http accesses

root/io/hadd/hadd_gen_input_files.C, root/io/hadd/merge_changeComp_check_output.C, root/io/hadd/merge_gen_input_tuples.C, root/ntuple/basics.C, root/ntuple/makeproject/rntuple/read_rntuple.cxx, root/ntuple/makeproject/rntuple/write_rntuple.cxx
Companion of https://github.com/root-project/root/pull/18080
=> [ntuple] RNTupleModel move out of Experimental

root/io/hadd/hadd_check_cms.C, root/io/hadd/merge_changeComp_check_output.C, root/io/hadd/merge_gen_input_tuples.C, root/ntuple/basics.C, root/ntuple/makeproject/rntuple/read_rntuple.cxx
Companion of https://github.com/root-project/root/pull/18225
=> [ntuple] RNTupleReader moved out of Experimental

root/io/bigevent/IoBigEventGeneration.cxx, root/io/bigevent/IoBigEventGenerator.cxx
Backport of https://github.com/root-project/root/pull/18495
=> Avoid sprintf deprecation warning in test

root/meta/naming/CMakeLists.txt, root/meta/naming/issue-18363/CMakeLists.txt, root/meta/naming/issue-18363/Objects.h, root/meta/naming/issue-18363/selection.xml, root/meta/naming/issue-18363/templateNameTest.C, root/meta/naming/issue-18363/templateNameTest.ref
https://github.com/root-project/root/issues/18363
=> Add roottest for name normalization issue [v6.36]

root/meta/naming/CMakeLists.txt, root/meta/naming/issue-18363/CMakeLists.txt, root/meta/naming/issue-18363/Objects.h, root/meta/naming/issue-18363/selection.xml, root/meta/naming/issue-18363/templateNameTest.C, root/meta/naming/issue-18363/templateNameTest.ref
https://github.com/root-project/root/issues/18363
=> Add roottest for name normalization issue [v6.32]

root/io/filemerger/CMakeLists.txt
Backport two commits from:
https://github.com/root-project/roottest/pull/1167
Goes together with this main ROOT PR:
https://github.com/root-project/root/pull/18765
=> Backport fixes for alma10

cling/dict/runoperators.C, cling/stl/default/VectorSort.C, python/basic/PyROOT_operatortests.py
Sister PR of:
* https://github.com/root-project/root/pull/18794
=> [v626] Backport fixes for alma10
