root-project/roottest

- root/dataframe/CMakeLists.txt
- root/dataframe/test_reduce.C
- root/dataframe/test_reduce.ref
`TDataFrame::Reduce` also supports branch types with no default constructor, but it seems that it was an overkill since it is not possible to have such objects in a `TTree`.
> [TDF] add test_reduce

- root/io/compression/Event.cxx
- root/io/compression/MainEvent.cxx
Previously, `4` was used to indicate an invalid compression algorithm number.
Bump this in preparation for assigning compression algorithm `4` to LZ4.
> Update constant for invalid compression algorithm.

- root/dataframe/CMakeLists.txt
- root/dataframe/regression_snapshot2.cxx
It tests jitting in the case of an empty-source TDataFrame (fixed by ROOT PR #662)
> [TDF] Add regression_snapshot2

- root/dataframe/CMakeLists.txt
This test was meant to check that TDF does not assume that the input
TTree has entries (formerly we crashed badly in the case of TTrees
with zero entries). Instead we see warnings coming from TChain due
to the reading of uninitialized memory. The test will be brought
back or deleted after we clarify whether a TTree with zero entries
is a case we want to support or not.
> [TDF] Take `regression_zeroentries` out until ROOT-8924 is solved

- cmake/modules/RootCTestMacros.cmake
This is needed to avoid copying the headers of externals (Vc and VecCore) to `${CMAKE_BINARY_DIR}/include` which forces us to inherit all warnings from Vc.
The change introduced here adds the necessary includes when running roottest tests.
See, e.g., https://github.com/root-project/root/pull/830#issuecomment-320942852 for examples of failing tests due to the missing includes.
> Add include directories for externals to include paths

- cling/dict/fwd-decl-stdless/.rootrc
- cling/dict/fwd-decl-stdless/CMakeLists.txt
- cling/dict/fwd-decl-stdless/execLessyTest.C
- cling/dict/fwd-decl-stdless/lessy.h
- cling/dict/fwd-decl-stdless/lessyLinkDef.h
Test for `std::less` forward decl from dictionary, which clang flags as invalid due to re-declared default arguments. This fixed an issue seen by CMS.
> Std less cms fwd decl

- root/io/filemerger/execTestMultiMerge.C
> Fixing new reference size for filemerger test in case of lzma_version < 5002

- root/dataframe/test_templateRecursionLimit.C
Fixes breakage introduced by PR #869 in `roottest/root`.
> [TDF] Fix test_templateRecursionLimit after interfaces changes in TDF

- root/meta/genreflex/noStreamer_noInputOperator/.rootrc
- root/meta/genreflex/noStreamer_noInputOperator/CMakeLists.txt
- root/meta/genreflex/noStreamer_noInputOperator/Makefile
- root/meta/genreflex/noStreamer_noInputOperator/customStreamer.C
- root/meta/genreflex/noStreamer_noInputOperator/customStreamer.ref
- root/meta/genreflex/noStreamer_noInputOperator/foo.h
- root/meta/genreflex/noStreamer_noInputOperator/foo_custom_input_operator.h
- root/meta/genreflex/noStreamer_noInputOperator/foo_custom_streamer.h
- root/meta/genreflex/noStreamer_noInputOperator/invalidNoInputOperatorGenreflex.ref
- root/meta/genreflex/noStreamer_noInputOperator/invalidNoInputOperator_selection.xml
- root/meta/genreflex/noStreamer_noInputOperator/invalidNoStreamerGenreflex.ref
- root/meta/genreflex/noStreamer_noInputOperator/invalidNoStreamer_selection.xml
- root/meta/genreflex/noStreamer_noInputOperator/noInputOperator_false_selection.xml
- root/meta/genreflex/noStreamer_noInputOperator/noInputOperator_selection.xml
- root/meta/genreflex/noStreamer_noInputOperator/noStreamer_false_selection.xml
- root/meta/genreflex/noStreamer_noInputOperator/noStreamer_selection.xml
What effect has `csr->SetRequestNoInputOperator(true);` on the dictionary generation?
I was expecting to find a `TBuffer &operator<<(TBuffer &buffer, const Foo *foo)` inside the dictionary if no input operator is set to false, but when I compared both options with:
```bash
diff -y roottest/root/meta/genreflex/noStreamer_noInputOperator/noInputOperator_rflx.cpp roottest/root/meta/genreflex/noStreamer_noInputOperator/noInputOperator_false_rflx.cpp
```
the only difference beside names was:
```
static ::ROOT::TGenericClassInfo 				      static ::ROOT::TGenericClassInfo 
instance("Foo", ::Foo::Class_Version(), "", 9,		         instance("Foo", ::Foo::Class_Version(), "", 9,
typeid(::Foo), ::ROOT::Internal::DefineBeha	                  typeid(::Foo), ::ROOT::Internal::DefineBeha …
```
> [genreflex] Add tests for noStreamer and noInputOperator xml attribute

- root/dataframe/CMakeLists.txt
- root/dataframe/test_columnoverride.cxx
It currently tests for `Define`s overriding a TTree branch.
It will be upgraded to also test for `Define`s overriding other
`Define`s as soon as we handle that case better.
> [TDF] Add test for handling of column re-Definition

- root/io/compression/Makefile
Sadly, when I forcibly create corruptions in the files (causing the LZ4 checksum to fail), the unittest crashes instead of exiting cleanly.
Regardless, corruptions cause this test to fail.
This tweak was done for https://github.com/root-project/root/pull/907 -- but can go in independently of that PR.
@pcanal
> Explicitly test LZ4 in the existing compression tests.

- root/io/filemerger/execTestMultiMerge.C
Synchronizing test references for LZ4 files
> Fixing filemerger references after adding LZ4 checksum functionality

- root/dataframe/test_columnoverride.cxx
- root/dataframe/test_templateRecursionLimit.C
Fix breakage introduced by [this PR](https://github.com/root-project/root/pull/924),
and test for redefinition of custom columns with the same name.
> [TDF] Upgrade tests after removal of "custom column"s from the functional graph

- root/meta/genreflex/ioreadrulesfailonwarning.eref
- root/meta/genreflex/noStreamer_noInputOperator/CMakeLists.txt
- root/meta/rootcling/CMakeLists.txt
Rootcling PR [#831](https://github.com/root-project/root/pull/831) fixes some erros with the return codes and the verbosity level. However, some tests actually test the old broken behavior. This PR updates those tests that #831 doesn't break master.
> Fix tests for root PR #831

- root/io/filemerger/execTestMultiMerge.C
Investigation doesn't show any data differences in histograms, comparison shows that for TH1F/TH2F was added extra bytes, not affecting data of histograms. Hsimple101.root reference was updated according hsimple.root (with hadd -f1 option and default ZLIB algorithm)
> Filemerger test fixes

- root/dataframe/regression_zeroentries.cxx
Test is expected to start failing after the fixes introduced by [979](https://github.com/root-project/root/pull/979).
> [TDF] Fix numeric_limits::min/lowest mismatch in regression test

- root/multicore/tThreadExecutor.cpp
Weird that it wasn't noticed before.
Not the most useful of the tests. Tests functionality but not thread safety as we're writing on an atomic, but the latter is well covered by the other tests.
> Replace non thread-safe test

- root/dataframe/test_reports.cxx
There are two kinds of instructions that are used for divisions, divss
and rcpss, which have different accuracy and may be picked up depending
on compiler optimization options. Using multiplications ensures that
division innacuracies will not affect the pass rates of the filters in
this test.
> Do not rely on divisions in dataframe reports test

- root/dataframe/test_reduce.C
The breaking change has been introduced by a PR in root [here](https://github.com/root-project/root/pull/1473).
> [TDF] Adapt test_reduce after removal of one overload

- python/common.py
- root/meta/rlibmapLauncher.py
I tried before, but incompatibilities with accepted options of `pytest.main` made some tests fail. If removing the options does not make any test fail, then we can merge this and update the bundled version of pytest, which is already quite old (2.5.2, and I have 3.2.2 on my computer). The problem with using the builtin is that if there is also another version in the system, several tests fail (e.g. roottest-python-basic-basic) due to incompatibility with new interfaces:
```
$ ctest -VV -R roottest-python-basic-basic
UpdateCTestConfiguration  from :/home/amadio/build/gcc7.3/DartConfiguration.tcl
Parse Config file:/home/amadio/build/gcc7.3/DartConfiguration.tcl
Add coverage exclude regular expressions.
SetCTestConfiguration:CMakeCommand:/usr/bin/cmake
UpdateCTestConfiguration  from …
```
> Try again to use a system version of pytest if available

- root/tree/cloning/CMakeLists.txt
- root/treeformula/event/EventLinkDef.h
Add missing dependency for hsimple.
In highly parallel builds we end up executing hsimple before ROOT is fully built. 
This patch fixes a regression seen in the master.
> Fixing parallel builds for roottest

- root/dataframe/CMakeLists.txt
- root/dataframe/read_leaves_nodict.ref
- root/dataframe/test_read_leaves.cxx
- root/dataframe/test_read_leaves.h
- root/dataframe/test_read_leaves_nodict.cxx
It seems the data read from `Filter(check_a_b, {"v.a", "v.b"})` is wrong, so the modified tests are expected to fail. To be investigated.
> [TDF] Improvements to test_read_leaves[_nodict]

- root/dataframe/test_read_leaves_nodict.cxx
Reverting a (harmless) copy-paste mistake
> [TDF] test_read_leaves_nodict should use no dictionaries

- root/io/json/STL.ref
- root/io/json/STL1.ref
- root/io/json/test_classes.h
TRef has custom streamer and not correctly supported by JSON I/O
> json: replace TRef class by TNamed class in testing

- root/meta/CMakeLists.txt
Follow up patch for 25b8f34a1f98b9af1199b5b27bcbff9870c4d9b6, as it was
excluding ROOT_MODULES which was cxxmodules not runtime_cxxmodules.
> [cxxmodules] Fix a test for modules

- cmake/modules/RootCTestMacros.cmake
- root/meta/CMakeLists.txt
This enables us to run tests only when certain ROOT feature is
enabled.
> Implement a REQUIRES clause for tests.

- cling/array/CMakeLists.txt
- cling/dict/fwd-decl-stdless/CMakeLists.txt
- cling/reflex/CMakeLists.txt
- cling/template/CMakeLists.txt
- root/aclic/misc/CMakeLists.txt
- root/core/CMakeLists.txt
- root/dataframe/CMakeLists.txt
- root/hist/formula/CMakeLists.txt
- root/html/CMakeLists.txt
- root/io/evolution/CMakeLists.txt
- root/io/json/CMakeLists.txt
- root/io/multizip/CMakeLists.txt
- root/io/newClassDef/CMakeLists.txt
- root/io/pointers/CMakeLists.txt
- root/math/genvector/CMakeLists.txt
- root/meta/CMakeLists.txt
- root/meta/ROOT-7462/CMakeLists.txt
- root/meta/autoloading/CMakeLists.txt
- root/meta/cmsUnload/CMakeLists.txt
- root/meta/enums/CMakeLists.txt
- root/meta/fwdDecls/CMakeLists.txt
- root/meta/genreflex/CMakeLists.txt
- root/treeformula/CMakeLists.txt
This excludes tests which are failing in runtime modules nightly builds.
We want to add runtime modules bot to incrementals and PRs so that
people can fix their bugs before commiting.
> [cxxmodules] Temporary excluding tests for adding cxxmodules to build bot

- root/meta/execUnloading.C
Because we're adding RAII in TCling::UpdateEnumConstant, transaction is
separated and we have to unload two transaction rather than one.
> Undo two transaction in execUnloading Enum

- root/meta/execUnloading.C
This reverts commit 732d4a30bfa402473640673bec1cc66bb32f43c6.
This depends on #2093. We removed RAII because we are not listening to
deserialization listener anymore.
I believe this fixes recent unstable execUnloading test.
> Revert "Undo two transaction in execUnloading Enum"

- python/basic/PyROOT_operatortests.py
Fixes PyROOT test of basic operators, which compares `str(...)` output to expectation. The behaviour changes with the new pretty-printing feature [in this PR to ROOT](https://github.com/root-project/root/pull/2097).
The changes are backward compatible because `repr(...)` is similar to `str(...)` in the old behaviour.
> [PyROOT] Fix operator test with new str behaviour

- root/io/stdarray/CMakeLists.txt
> Disable write_5 tests: source file does not exist:

- root/io/treeForeign/testForeignDrawLZ4.ref
Corresponds to https://github.com/root-project/root/pull/2775
Looks like setting `fLenType` in the `TLeafElement` resulted in a very small compression ratio change in one of the unittests.  This is the corresponding change.
> Update LZ4 test to reflect change in compression ratio.

- cmake/modules/SearchInstalledSoftwareRoottest.cmake
In particular, needed when building googletest.
Original patch by chrisburr at https://github.com/root-project/root/pull/2995
> Pass through CMAKE_AR when building external projects

- CMakeLists.txt
- cmake/modules/RootCTestMacros.cmake
This allows roottest to be checked out outside ROOT's source tree. Now we
rely on the list of options/features provided by the ROOTConfig.cmake.
This patch should fix ROOT-9405.
> [cmake] Make roottest independent on ROOT_SHOW_OPTIONS.

- python/pytest/_pytest/assertion/rewrite.py
This PR ports a fix to ROOT's pytest to get rid of these error:
http://cdash.cern.ch/testDetails.php?test=57901667&build=598659
The fix has been picked from a pytest PR:
https://github.com/pytest-dev/pytest/pull/801
The objective is to properly handle the calls to Ast Call depending on the Python version, since its signature changed in Python3.5.
> Fix call to Ast Call in pytest for Python3

- python/pytest/_pytest/assertion/rewrite.py
This commit ports a fix to ROOT's pytest to get rid of these error:
http://cdash.cern.ch/testDetails.php?test=57901667&build=598659
The fix has been picked from a pytest PR:
https://github.com/pytest-dev/pytest/pull/801
The objective is to properly handle the calls to Ast Call
depending on the Python version, since its signature changed
in Python3.5.
> Fix call to Ast Call in pytest for Python3 (Port 6.16)

- python/cpp/PyROOT_advancedtests.py
- python/cpp/Template.C
This tests the failing cases described here:
https://sft.its.cern.ch/jira/browse/ROOT-9836
> [ROOT-9836] Add test for templated function in a namespace

- python/JupyROOT/CMakeLists.txt
Backport of https://github.com/root-project/roottest/pull/268
> Adapt doctest tests to reorganization in JupyROOT directory (backport 6.16)

- python/JupyROOT/CMakeLists.txt
- python/JupyROOT/nbdiff.py
- python/JupyROOT/thread_local.ipynb
Improve notebook testing via nbdiff
- Add suffix "notebook" to tests which run notebooks
- Allow to run root notebooks
- Add new thread_local notebook to test that every cell is executed within the same thread
- Add to the battery the existing root notebooks previously disabled
> [JupyROOT] C++Kernel: do not run each cell in a separate thread

- CMakeLists.txt
- cling/functionTemplate/CMakeLists.txt
- python/JupyROOT/CMakeLists.txt
- python/basic/CMakeLists.txt
- python/cling/CMakeLists.txt
- python/cmdLineUtils/CMakeLists.txt
- python/cpp/CMakeLists.txt
- python/function/CMakeLists.txt
- python/memory/CMakeLists.txt
- python/pickle/CMakeLists.txt
- python/pythonizations/CMakeLists.txt
- python/regression/CMakeLists.txt
- python/stl/CMakeLists.txt
- python/ttree/CMakeLists.txt
- root/roofitstats/CMakeLists.txt
A number of test failures have to be fixed in the experimental PyROOT builds:
https://epsft-jenkins.cern.ch/job/root-exp-pyroot/9/
This PR temporarily flags those tests as "will fail" for the experimental PyROOT builds, and they will be restored progressively as they are fixed.
> [Exp PyROOT] Flag tests that now fail in PyROOT experimental

- python/cmdLineUtils/CMakeLists.txt
To address:
https://epsft-jenkins.cern.ch/job/root-exp-pyroot/12/
> [Exp PyROOT] Disable cleanup tests, watch out with Py3 builds

- root/dataframe/CMakeLists.txt
Otherwise, when building roottest against a pre-existing ROOT
installation, libTreePlayer is not linked.
This explicit dependency on libTreePlayer can be removed once the
ROOTDataFrame target transitively brings in its dependencies also
when building roottest against a pre-existing ROOT installation.
@amadio how do we test that this resolves the failures you were seeing?
> [DF] Add TreePlayer as an explicit dependency for tests

- cling/dict/ROOT-9110/CMakeLists.txt
- cmake/modules/RootMacros.cmake
Does the same as for ROOT_GENERATE_DICTIONARY (just forwards).
Otherwise, flags will be misinterpreted as header files.
> Add "OPTIONS" flag to ROOTTEST_GENERATE_DICTIONARY:

- python/cmdLineUtils/CMakeLists.txt
- python/regression/CMakeLists.txt
Re-enable the tests of the Python command line tools, which benefit from pythonisations added by these two PRs:
- https://github.com/root-project/root/pull/3370 (already merged)
- https://github.com/root-project/root/pull/3387 (to be merged)
> [Exp PyROOT] Re-enable command line utils tests

- python/regression/CMakeLists.txt
After re-enabling `root_6023`, which uses Cppyy directly, an equivalent fix to the one of:
https://github.com/root-project/roottest/commit/82d1ac9264d731e173a13629d8483674875299b9
is needed for the test to find the location of the `libcppyy_backend` library on MacOS.
> [Exp PyROOT] Set environment to find libcppyy_backend on MacOS

- root/io/filemerger/CMakeLists.txt
- root/tree/fastcloning/execCheckClusterRange.ref
- root/tree/fastcloning/execCheckClusterRange.ref32
This is the corresponding roottest change for https://github.com/root-project/root/pull/1534 because our tests are apparently sensitive to the size of comments ?!?!
> Tweak small change in tree size.

- root/multicore/CMakeLists.txt
- root/multicore/generate_imt_tree.C
- root/multicore/ttree_read_imt.cpp
- root/multicore/ttree_read_imt.ref
- root/multicore/ttree_read_imt.sh
- root/multicore/ttree_read_imt_allpar.cpp
- root/multicore/ttree_read_imt_allpar.sh
On 32bit, generating that file takes > 5 minutes. It is also a nice
exercise to do IMT reads across the network!
> multicore: read ttree_read_imt.root from http://root.cern:

- python/basic/PyROOT_basictests.py
- python/function/PyROOT_functiontests.py
This PR modifies `roottest-python-basic-basic` and `roottest-python-function-function` to adapt them to the new experimental PyROOT and its new Cppyy. Every commit explains the reason for the corresponding changes.
It is expected that, after these modifications, both tests will still fail. In the case of  `roottest-python-basic-basic`, there is still this issue:
https://sft.its.cern.ch/jira/browse/ROOT-10041
As for `roottest-python-function-function`, there is this remaining issue:
https://sft.its.cern.ch/jira/browse/ROOT-10029
Both issues have already been fixed in the Cppyy repos and will be incorporated in the next Cppyy update for PyROOT experimental.
> [Exp PyROOT] Make tests compliant with new Cppyy

- python/regression/CMakeLists.txt
- root/meta/tclass/regression/CMakeLists.txt
Just setting `CLING_STANDARD_PCH` to `none` will prevent Cppyy from checking the PCH.
This will fix the test failure from last night in PyROOT experimental:
https://epsft-jenkins.cern.ch/job/root-exp-pyroot/79/
> [Exp PyROOT] No need to specify URL of PCH to Cppyy

- root/dataframe/CMakeLists.txt
- root/dataframe/test_progressiveCSV.cxx
- root/dataframe/test_progressiveCSV.ref
- root/dataframe/test_progressiveCSV.sh
Change test to check when new lines of CSV file are read. The previous strategy, which consisted in checking the resident memory of the process before and after running the RDF computation, was not reliable and made the test fail intermittently.
> Change test to check when new lines of CSV file are read

- root/io/json/Makefile
- root/io/json/Map.ref
- root/io/json/runMap.C
Testing new funcitonlaity to store special kinds of map as JSON object.
Such representation is much more compact than default one.
But works only for limited usecases, therefore cannot be used by
default.
> json: test writing and reading std::map as JSON object

- python/cling/CMakeLists.txt
- python/cling/runPyAPITestCppyy.C
This PR needs to be merged after https://github.com/root-project/root/pull/3731, since it needs the `RPyROOTApplication` functionality for wrapping ROOT warnings into Python warnings.
> [Exp PyROOT] Fix roottest-python-cling tests

- python/function/CMakeLists.txt
- python/function/PyROOT_functiontests.py
In the new Cppyy, `double&` is `ctypes.c_double` in Python and therefore the assignment needs to be done to its value attribute, see:
https://sft.its.cern.ch/jira/browse/ROOT-10029
> [Exp PyROOT] Use correct Python type in test python-function

- root/io/newClassDef/featuretest/Class.C
- root/io/newClassDef/featuretest/Class.h
This causes a test failure with clang-HEAD on Ubuntu 18.04.
> Cannot #define private public for STL!

- root/io/newClassDef/featuretest/ClassTrick.C
This is suppopsed to fix the test issue with clangHEAD:
Info in <TUnixSystem::ACLiC>: creating shared library /mnt/build/wsincrmaster/LABEL/ROOT-ubuntu1804-clangHEAD/SPEC/noimt/roottest/root/io/newClassDef/featuretest/ClassTrick_C.so
In file included from input_line_14:18:
In file included from /mnt/build/wsincrmaster/LABEL/ROOT-ubuntu1804-clangHEAD/SPEC/noimt/build/include/root_std_complex.h:13:
In file included from /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/complex:45:
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/sstream:301:14: error: '__xfer_bufptrs' redeclared with 'public' access
struct __xfer_bufptrs
^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/sstream:67:14: note: previously declared 'private' here
struct __xfer_bufptrs;
^
Error in …
> Do not leave "#define private public" in interpreter!

- root/meta/MemberComments.ref
Fix error appeared in https://github.com/root-project/root/pull/3876
In principle, one could restore original order of methods again.
> changes after fixes of gcc9 warnings

- root/io/CMakeLists.txt
We fail only when running roottest/root/io/tuple tests.
> [cxxmodules] Narrow the excluded tests.

- python/basic/CMakeLists.txt
Change needed to enable the above mentioned test.
> [Exp PyROOT] Roottest-python-basic-operator enabled

- cling/functionTemplate/cintrun.ref-cling
- cling/functionTemplate/pythoncintrun.ref
- python/cpp/PyROOT_advancedtests.py
Fixes for tests as a result of the changes in https://github.com/root-project/root/pull/3911
> [metacling & PyROOT] Adapt to TClingMethodInfo not iterating anymore over template instantiations

- root/io/CMakeLists.txt
> [cxxmodules] Remove workaround due to root-project/root#3990.

- python/cpp/CMakeLists.txt
- python/cpp/PyROOT_advancedtests.py
Note: the test `roottest-python-cpp-advanced` can't be fully re-enabled until the resolution of these two Cppyy issues:
- https://bitbucket.org/wlav/cppyy/issues/113/
- https://bitbucket.org/wlav/cppyy/issues/115/
> [Exp PyROOT] Adapt python-cpp-advanced to new Cppyy

- python/cpp/PyROOT_advancedtests.py
This is a new round of modifications for `roottest-python-cpp-advanced` to work with PyROOT experimental. The test is not fully working yet because of two pending issues:
- https://bitbucket.org/wlav/cppyy/issues/113 : fixed in CPyCppyy's repo, an update of the PyROOT's copy of Cppyy is needed to incorporate it. Trying to cherry pick only the related changes results in new crashes in the same test that might be caused by missing previous changes in Cppyy. To be checked.
- https://bitbucket.org/wlav/cppyy/issues/121
> [Exp PyROOT] More modifications for python-cpp-advanced

- cling/operator/EqualTest.ref-cling
- cling/operator/EqualTest_convert.sh
If the declaration comes from an AST file no source locations are printed.
This patch is in the same direction as we took in root-project/roottest@3a8dfca4
This is part of root-project/root#3850
> [cxxmodules] Filter out source locations.

- python/cling/runPyAPITestCppyy.C
This is related to: https://github.com/root-project/root/pull/4051
The PR adapts one test to CPyCppyy v1.8.2
> [Exp PyROOT] Small test update after Cppyy update

- python/memory/CMakeLists.txt
- python/memory/PyROOT_memorytests.py
Changes are mainly motivated by the change in the default memory policy (now is `kUseStrict`, used to be `kUseHeuristics`).
> [Exp PyROOT] Adapt python-memory test to new Cppyy

- python/pythonizations/CMakeLists.txt
- python/pythonizations/PyROOT_smartptrtest.py
The test mentioned in the title was fixed. The problem was simply that the attribute `_get_smart_ptr` became `__smartptr__` in new Cppyy.
> [Exp PyROOT] Test fixed: pythonizations-smartptr

- python/pythonizations/PyROOT_smartptrtest.py
In smartptr test, ROOT needed to be imported because in MacOs if a cppyy environment variable is not set, libcppyy_backend is not found.
> [Exp PyROOT] Added 'import ROOT' in smartptr test

- python/pythonizations/CMakeLists.txt
- python/pythonizations/PyROOT_pythonizationtest.py
The test mentioned in the title was fixed thanks to commit e2c3fd4 in the ROOT repository and to some changes in the syntax in order to match the new Cppyy names of some variables and methods.
> [Exp PyROOT] Test fixed: pythonizations-pythonizations

- python/pythonizations/PyROOT_pythonizationtest.py
In pythonizations test, ROOT needed to be imported because in MacOs if a cppyy environment variable is not set, libcppyy_backend is not found.
> [Exp PyROOT] Added 'import ROOT' in pythonizations test

- python/cpp/PyROOT_cpptests.py
Issue reported in ROOT-8935.
Linked with https://github.com/root-project/root/pull/4202
> [PyROOT] Add test for negative enum values accessed via a namespace

- python/cpp/PyROOT_cpptests.py
> [PyROOT] Backport 6.18: Add test for negative enum values accessed via a namespace

- python/cling/CMakeLists.txt
- python/cling/runPyAPITestCppyy.C
Cppyy's TPython is temporarily disabled due to some broken functionality:
https://bitbucket.org/wlav/cppyy/issues/65
> [Exp PyROOT] Rely on PyROOT's TPython for roottest-python-cling

- cmake/modules/RoottestMacros.cmake
- root/math/vdt/CMakeLists.txt
Before, also already parsed arguments were potentially added as sources. "Potentially", because files that were not found were silently not added (like `LIBRARIES`, `Core` etc...)
Now, files that don't exist at configuration time *are* added (because they might be generated later, during build!). That now causes nice errors when an argument is misinterpreted as source file (e.g. misspelled parameter name).
> Cmake: tighten ROOTTEST_GENERATE_EXECUTABLE

- root/meta/rootcling-modules/module-dep-order/CMakeLists.txt
This fixes the test when run in incremental builds, where on a clean build the test passes but it fails on the next build because the files were already generated.
> [cxxmodules] Clean up the implicitly build module file.

- python/basic/CMakeLists.txt
Fix nightly test failure in MacOS:
https://epsft-jenkins.cern.ch/job/root-exp-pyroot/LABEL=mac1014,SPEC=default/235/testReport/projectroot.roottest.python/basic/roottest_python_basic_overload/
> [Exp PyROOT] For MacOs, tell Cppyy location of libcppyy_backend

- root/meta/MakeProject/create_makeproject_examples.C
The test has subtest which are testing the automatic loading and the project
generation in root. In the former case the module.modulemap file needs to be
present. In the latter case needs to be gone so that we can trigger the
generation of a new project.
The approach of this patch is not the best, however it is unclear if we can
split the logic into multiple tests without a slowdown or generating the same
input/output multiple times.
> [cxxmodules] Enable and disable the module.modulemap file.

- python/regression/CMakeLists.txt
- python/regression/PyROOT_regressiontests.py
- python/stl/CMakeLists.txt
- python/stl/PyROOT_stltests.py
This contributes to fix:
- roottest-python-stl-stl
- roottest-python-regression-regression
Goes together with: https://github.com/root-project/root/pull/4334
A relevant cppyy ticket is:
https://bitbucket.org/wlav/cppyy/issues/157
> [Exp PyROOT] Fixes for tests in roottest-python

- root/meta/rootcling-modules/module-dep-order/CMakeLists.txt
POSTCMD is not executed when the test fails. CMake aborts with FATAL_ERROR.
> [cxxmodules] Clean up with a PRECMD.

- python/cpp/PyROOT_cpptests.py
Goes together with https://github.com/root-project/root/pull/4386
> [Exp PyROOT] AsCObject is now called as_cobject in Cppyy

- root/meta/naming/execCheckNaming.ref
- root/meta/naming/execResolveTypedef.cxx
- root/meta/naming/execResolveTypedef.ref
This is needed to solve ROOT-10337.
```
root [0] struct Complex {};
root [1] auto v = std::vector<Complex>{};
root [2] TClassEdit::ResolveTypedef("std::vector<Complex>::value_type")
(std::string) "std::Complex"
```
> No longer strip/ignore std in ResolveTypedef.  Adapt reference file.

- root/meta/MakeProject/CMakeLists.txt
- root/meta/MakeProject/create_makeproject_examples.C
This patch moves the deletion of the stl_example.root in the test so that
we could use the POSTCMD and PRECMD to rename the modulemap file, activating it
before the particular test and deactivating it for the next tests.
> [cxxmodules] Rename the modulemap file before the test starts.

- cling/exception/CMakeLists.txt
- cling/functionTemplate/CMakeLists.txt
- cling/specialobj/CMakeLists.txt
- cling/specialobj/f02.ref
- root/rint/CMakeLists.txt
Fixes 2 tests for cxxmodules MacOSX builds http://cdash.cern.ch/testDetails.php?test=67555125&build=685983 && http://cdash.cern.ch/testDetails.php?test=67555125&build=685983
Originally test gives incorrect results also on non-cxxmodules build (ubuntu), but it is always green because expected output is test failure:
```
-- TEST COMMAND -- 
cd /mnt/build/night/LABEL/ROOT-ubuntu1804-clangHEAD/SPEC/cxxmod-noimt/V/6-18/build/roottest/cling/exception
/usr/bin/timeout -s USR2 270s root -l -b -q -e ''int*p=nullptr' *p'
-- BEGIN TEST OUTPUT --
-- END TEST OUTPUT --
-- BEGIN TEST ERROR --
Warning in <TApplication::GetOptions>: macro *p' not found
ROOT_cli_0:1:1: warning: missing terminating ' character [-Winvalid-pp-token]
'int*p=nullptr
^
ROOT_cli_0:1:1: error: expected expression
-- END TEST …
```
> [cxxmodules] Fix tests for cxxmodules build on MacOSX

- python/cpp/PyROOT_advancedtests.py
Test the forward compatibility feature introduced in old PyROOT to also allow square bracket when instantiating function templates, in addition to parentheses.
Goes together with:
https://github.com/root-project/root/pull/4639
> [PyROOT] Test square bracket syntax for template instantiation

- python/cpp/PyROOT_advancedtests.py
- python/function/PyROOT_functiontests.py
- python/regression/PyROOT_regressiontests.py
They are still present in the old PyROOT, but when used they throw a deprecation warning.
Goes together with https://github.com/root-project/root/pull/4650
> [Exp PyROOT] Long and Double are not present in new PyROOT

- cling/functionTemplate/CMakeLists.txt
- cling/functionTemplate/testcint.py
Goes together with:
https://github.com/root-project/root/pull/4733
and prevents this test failure caused by the newly introduced deprecation warning:
https://epsft-jenkins.cern.ch/job/root-pullrequests-build/74251/testReport/projectroot.roottest.cling/functionTemplate/roottest_cling_functionTemplate_testcint/
> [PyROOT] Use new square bracket syntax to prevent deprecation warning

- python/cpp/PyROOT_cpptests.py
Goes together with: https://github.com/root-project/root/pull/4753
Both in old PyROOT and in new Cppyy, when copy constructing a
pre-existing object, i.e. with the syntax `x.__init__(y)`,
the Python proxy for x is reassigned to the new value of C++ x
after the copy construction, and both the proxy and the new
C++ object are registered as a new pair in the memory regulator.
However, the old C++ object still exists (although it is not
pointed by any Python proxy anymore), which can cause a memory
leak if the Proxy owned the C++ object; furthermore, the old
C++ object is still registered in the memory regulator with
its old proxy.
Consequently, `x.__init__(y)` should be discouraged if x already
points to a C++ object. Instead, we change this test to:
1. Use `x.__init__(y)` when x is a proxy …
> [Exp PyROOT] Test copy construction from nullptr and __assign__

- python/regression/PyROOT_regressiontests.py
- root/io/const/constTest.C
The Darwin module exposes more names when enabled. Thus we get a diagnostic that `normal` and `Handle` are being redefined.
This patch should fix 2 failing tests on OSX when runtime_cxxmodules=On
Patch by Alexander Penev(@alexander-penev)!
> [cxxmodules] Avoid name clashes which are already defined by MacTypes.h

- root/meta/execTypedefList.C
- root/meta/typelist.v6.txt
No longer defined in TGFileBrowser
Should be applied after https://github.com/root-project/root/pull/4887
> Remove TGFileBrowser::mFiltered_i from list of classes

- python/pythonizations/PyROOT_pythonizationtest.py
Now this is done with a pythonization, until the bindings handle
the injection of the using overloads.
Goes together with https://github.com/root-project/root/pull/4916
> [PyROOT][ROOT-7983] Test injection of overloads for createHistogram

- root/meta/execTypedefList.C
- root/meta/typelist.v6.txt
TLego and TPainter3dAlgorithms were removed from public includes
> Exclude TLego from v6 types list

- python/regression/PyROOT_regressiontests.py
Goes together with https://github.com/root-project/root/pull/4980
[skip-ci]
> [Exp PyROOT][ROOT-9040] Test kMustCleanup not set for proxied objects

- root/hist/operator/runcopy.C
Appears when ROOT build with "less_includes" option
> Add missing TList.h in hist/operator/runcopy.C macro

- root/meta/evolution/execMissingCheckSum.cxx
May appear after optimizing ROOT includes
> add potentially missing include in execMissingCheckSum.cxx [skip-ci]

- root/tree/friend/zmumuSelDrawmail.cpp
Appears after enabling "less_includes" options
> Add missing include TBranch.h in tree/friend tests

- python/JupyROOT/CMakeLists.txt
- python/JupyROOT/nbdiff.py
This test failure was observed:
http://cdash.cern.ch/testDetails.php?test=81587595&build=834646
because in the Cpp_IMT_Canvas notebook test, the output notebook
notebook is compared with the input notebook to decide if the
test succeeded. It seems that the text representation of the
image encoded in the notebook can be different depending on
the platform, making the diff fail and the test too, whereas
the test actually succeeded.
Since the aim of the test is just to check if drawing an (empty)
canvas runs without error in implicit MT mode, it is enough to check
that the exit status of the process that runs the notebook is zero.
> [Notebooks] Don't compare output, just check it runs successfully

- python/pythonizations/PyROOT_pythonizationtest.py
In old PyROOT, on MacOS, the iterator for RooArgSet is not
constructed correctly (the next method is not injected).
This is fixed in new Cppyy (and therefore experimental PyROOT).
> [Exp PyROOT] Enable test only for experimental PyROOT

- root/dataframe/test_chainZombieFile.C
- root/dataframe/test_typeguessing.cxx
Fixes test failures seen in `chainZombieFIle` and `typeguessing` tests at https://github.com/root-project/root/pull/5207
> [DF] Adapt tests now that RDF throws if there is an error during the event loop

- root/roofitstats/CMakeLists.txt
This only shows when roottest is built outside of ROOT.
> [RF] Add missing library to roofit's stability tests.

- root/io/filemerger/CMakeLists.txt
- root/tree/fastcloning/references/execCheckClusterRange.ref32
- root/tree/fastcloning/references/execCheckClusterRange_builtinzlib.ref
- root/tree/fastcloning/references/execCheckClusterRange_zlib.ref
By switching the TStreamerSTL from being modified then stored to
storing a copy created on the stack, the kIsOnHeap bit is change and since
that information is store, the onfile representation (and thus after compression
size) change a bit.
> Follow fix needed for ROOT-10648.

- python/JupyROOT/nbdiff.py
In case a test machine is overloaded and the default 1-minute
timeout fires up, but there is no real error.
To check if this intermittent failure ("kernel didn't respond...") observed on root-fedora29-3:
http://cdash.cern.ch/testDetails.php?test=83240520&build=852667
is due to eventual high load on the node. When running the test alone on the same node 100 times, not a single failure happens.
> [Notebooks] Increase kernel timeout to 3 minutes

- cmake/modules/RoottestMacros.cmake
When ROOT is built with address sanitizier enabled, ROOTTEST exectuables
need to link against ROOT's sanitizer config to build correctly.
> [CMake] Make executables link against sanitizer config.

- root/dataframe/test_foreach.cxx
The former is deprecated in favor of the latter.
> Substitute usages of GetImplicitMTPoolSize with GetThreadPoolSize

- python/JupyROOT/CMakeLists.txt
- python/JupyROOT/doctest_launcher.py
- python/JupyROOT/nbdiff.py
The JupyROOT tests have several dependencies:
1. Doctests: IPython
2. Python kernel tests: jupyter (for nbconvert), which also pulls IPython
3. C++ kernel tests: jupyter and metakernel
This PR moves the check for these test dependencies at runtime instead of at build time.
> [JupyROOT] Replace CMake checks by runtime checks for test dependencies

- root/io/filemerger/CMakeLists.txt
- root/tree/fastcloning/references/execCheckClusterRange_builtinzlib.ref
- root/tree/fastcloning/references/execCheckClusterRange_zlib.ref
By switching the TStreamerSTL from being modified then stored to
storing a copy created on the stack, the kIsOnHeap bit is change and since
that information is store, the onfile representation (and thus after compression
size) change a bit.
> Backport follow-up fix needed for ROOT-10648.

- python/JupyROOT/CMakeLists.txt
The envvar is set in `root-build.cmake` and added in the PR here: https://github.com/root-project/rootspi/pull/79
> [JupyROOT] Add envvar to veto tests

- python/JupyROOT/nbdiff.py
Backport fix to 6.16 to solve these errors:
http://cdash.cern.ch/viewTest.php?onlyfailed&buildid=874956
> [JupyROOT] Tolerate differences due to different python versions

- python/JupyROOT/CMakeLists.txt
Prevent the creation of .ipynb, .C, .pcm, .d and .so temporary
files in the source directory. Such remnants can cause
failures in the JupyROOT tests, e.g:
https://github.com/root-project/root/pull/5577#issuecomment-625671277
> [JupyROOT] Run tests in build directory

- cmake/modules/RoottestMacros.cmake
- root/io/filemerger/CMakeLists.txt
1. When running tests, one cannot use dependency from normal targets. 
Therefore, in `filemerger` create/copy hsimple.root file using extra tests targets and assign dependency from them
2. `TIMEOUT` parameter in ROOTTEST_ADD_TEST can only have single value
3. When generate dictionary, use name of dictionary directly - not a global variable which may change in the future
> Add hsimple copying test rule in file merger

- python/JupyROOT/CMakeLists.txt
Prevent the creation of .ipynb, .C, .pcm, .d and .so temporary
files in the source directory. Such remnants can cause
failures in the JupyROOT tests.
> [JupyROOT] Backport 6.20: Run tests in build directory

- python/JupyROOT/CMakeLists.txt
Prevent the creation of .ipynb, .C, .pcm, .d and .so temporary
files in the source directory. Such remnants can cause
failures in the JupyROOT tests.
> [JupyROOT] Backport 6.18: Run tests in build directory

- python/JupyROOT/CMakeLists.txt
Prevent the creation of .ipynb, .C, .pcm, .d and .so temporary
files in the source directory. Such remnants can cause
failures in the JupyROOT tests.
> [JupyROOT] Backport 6.16: Run tests in build directory

- root/multicore/CMakeLists.txt
As dependency, one should provide real tests names
Also add dependency on ROOT libs when generate dictionary
> Try to fix multicore test dependency

- python/JupyROOT/CMakeLists.txt
Jupyter processes are not meant to run concurrently. In particular,
we observed issues with jupyter-migrate trying to concurrently create
the `kernels` directory and with jupyter processes fighting over
sockets.
> Never run two JupyROOT tests concurrently

- CMakeLists.txt
- python/CMakeLists.txt
- python/basic/CMakeLists.txt
- python/basic/PyROOT_basictests.py
- python/basic/PyROOT_datatypetest.py
- python/basic/PyROOT_overloadtests.py
- python/cling/CMakeLists.txt
- python/cpp/CMakeLists.txt
- python/cpp/PyROOT_advancedtests.py
- python/cpp/PyROOT_cpp11tests.py
- python/cpp/PyROOT_cpptests.py
- python/function/CMakeLists.txt
- python/function/PyROOT_functiontests.py
- python/memory/CMakeLists.txt
- python/memory/PyROOT_memorytests.py
- python/pickle/CMakeLists.txt
- python/pickle/PyROOT_readtests.py
- python/pickle/PyROOT_writetests.py
- python/pythonizations/CMakeLists.txt
- python/pythonizations/PyROOT_pythonizationtest.py
- python/pythonizations/PyROOT_smartptrtest.py
- python/regression/CMakeLists.txt
- python/regression/PyROOT_regressiontests.py
- python/stl/CMakeLists.txt
- python/stl/PyROOT_stltests.py
- python/ttree/CMakeLists.txt
- python/ttree/PyROOT_ttreetests.py
... and to the creation of the pyroot_legacy flag
Backport of https://github.com/root-project/roottest/pull/531
> [PyROOT] 6.22 Backport: Adapt tests to removal of pyroot_experimental flag

- root/math/unuran/CMakeLists.txt
unuran tests will be enabled in ROOT itself after merging https://github.com/root-project/root/pull/5828
> Disable unuran tests - now in ROOT itself

- root/treeproxy/make_tuple_draw.C
Problem appears while `<iomanip>` is not provided by used ROOT includes
I just used directly `ostream::precision` method.
Is there way to add extra includes in code generated by `TTree::MakeProxy()`
> Do not use iomanip from TTree::MakeProxy in treeproxy test

- root/dataframe/CMakeLists.txt
The `dataframe` cmake variable is not set when roottest is built
indepdendently against a pre-installed ROOT. ROOT_dataframe_FOUND
should be set both then and when roottest is built together with ROOT.
> Fix check for RDF feature when roottest is built independently

- root/dataframe/CMakeLists.txt
- root/dataframe/test_trainCache.C
- root/meta/evolution/CMakeLists.txt
- root/meta/evolution/writefile.C
- root/meta/loadAllLibs/CMakeLists.txt
- root/tree/cloning/references/exectrimZLIB_i686_win32.ref
- scripts/CMakeLists.txt
Following the latest changes in ROOT, some test are now working (then remove the WILLFAIL flag), and mark the forgotten failing ones as WILLFAIL
> Fix (or disable) remaining failg tests on Windows

- CMakeLists.txt
- cling/stl/dicts/CMakeLists.txt
- cmake/modules/RoottestMacros.cmake
- root/tree/cloning/CMakeLists.txt
- Properly set `PYTHONPATH` for CMake
- Add missing `--config $<CONFIG>` for `roottest-cling-stl-dicts-build`, preventing to trigger a full rebuild of ROOT
> Fix non-standalone roottest on Windows

- python/cpp/PyROOT_advancedtests.py
It tests that the boolean semantics for exception objects are
well defined, as well as the absence of a teardown crash
that was reported in ROOT-10870.
Goes together with https://github.com/root-project/root/pull/6024
> [PyROOT][ROOT-10870] Add test for boolean value of exceptions

- root/roofitstats/vectorisedPDFs/CMakeLists.txt
- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h
- root/roofitstats/vectorisedPDFs/testAddPdf.cxx
- root/roofitstats/vectorisedPDFs/testArgusBG.cxx
- root/roofitstats/vectorisedPDFs/testBernstein.cxx
- root/roofitstats/vectorisedPDFs/testBifurGauss.cxx
- root/roofitstats/vectorisedPDFs/testBreitWigner.cxx
- root/roofitstats/vectorisedPDFs/testBukin.cxx
- root/roofitstats/vectorisedPDFs/testCBShape.cxx
- root/roofitstats/vectorisedPDFs/testChebychev.cxx
- root/roofitstats/vectorisedPDFs/testChiSquarePdf.cxx
- root/roofitstats/vectorisedPDFs/testCompatMode.cxx
- root/roofitstats/vectorisedPDFs/testDstD0BG.cxx
- root/roofitstats/vectorisedPDFs/testExponential.cxx
- root/roofitstats/vectorisedPDFs/testGamma.cxx
- root/roofitstats/vectorisedPDFs/testGauss.cxx
- root/roofitstats/vectorisedPDFs/testLandau.cxx
- root/roofitstats/vectorisedPDFs/testLegendre.cxx
- root/roofitstats/vectorisedPDFs/testLognormal.cxx
- root/roofitstats/vectorisedPDFs/testNovosibirsk.cxx
- root/roofitstats/vectorisedPDFs/testPoisson.cxx
- root/roofitstats/vectorisedPDFs/testPolynomial.cxx
- root/roofitstats/vectorisedPDFs/testVoigtian.cxx
- Commit tests that were left unfinished by EM.
- Reduce run times of many tests.
- Stabilise test that were marked `WILLFAIL`.
> [RF] Test for vectorised PDFs: Add tests and reduce run times

- root/meta/MemberComments.ref
- root/meta/genreflex/TClass/execbasic.ref
- root/meta/method/execTemplate.ref
Update ref files, now that TClass printing / TMethod iteration skips
deleted functions. This happens e.g. for const members, where the
compiler-generated op= is deleted.
> TClingMethodInfo now skips deleted functions:

- root/meta/MemberComments.ref
- root/meta/genreflex/TClass/execbasic.ref
- root/meta/method/execTemplate.ref
Backport of https://github.com/root-project/roottest/pull/572
> Backport 622: TClingMethodInfo now skips deleted functions

- root/meta/MemberComments.ref
- root/meta/genreflex/TClass/execbasic.ref
- root/meta/method/execTemplate.ref
> Backport 620: TClingMethodInfo now skips deleted functions:

- python/pytest/_pytest/assertion/rewrite.py
The issue was detected when running roottest with a conda ROOT
installation:
https://lcgapp-services.cern.ch/root-jenkins/view/conda/job/conda-nightlies/90/testReport/projectroot.python/pythonizations/roottest_python_pythonizations_pythonizations/
The fix corresponds to the following upstream pytest fix:
https://bitbucket.org/pytest-dev/pytest/commits/ce3f55c10452
> [Pytest] Fix incompatibility issue with Python>=3.8.4

- root/dataframe/CMakeLists.txt
- root/meta/MemberComments_win32.ref
Remove `${WILLFAIL_ON_WIN32}` on several dataframe tests that are now working on Windows and fix a Windows specific reference file
> Fix remaining failing tests on Windows

- root/roofitstats/CMakeLists.txt
- root/roofitstats/stabilityTests.cxx
- remove the `.so` file extension
- disable the test which is failing after the add of RooHelpers::HijackMessageStream
> Disable roofitstats/stabilityTests on Windows

- python/cling/cppyy_backend_check.h
- python/cling/runPyAPITestCppyy.C
- python/cling/runPyClassTest.C
If not, unset the environment variable. This will give to cppyy
the opportunity to find the library on its own, by looking in its
default directories.
This should solve this kind of failures in the conda builds:
https://lcgapp-services.cern.ch/root-jenkins/view/conda/job/conda-nightlies/104/testReport/projectroot.python/cling/roottest_python_cling_api/
which are due to the fact that the tests are run in standalone
mode and, therefore, {CMAKE_BINARY_DIR}/lib does not contain
the ROOT libraries.
> [PyROOT] Check if CPPYY_BACKEND_LIBRARY points to an existing file

- root/dataframe/readShip.C
Column type is RVec<int>, not int, and RDF gets it wrong.
https://github.com/root-project/root/pull/6258 fixes the type inference
problem (and therefore this test) for master.
> [DF] Fix test for ROOT-9674

- root/dataframe/readShip.C
Column type is RVec<int>, not int, and RDF gets it wrong.
https://github.com/root-project/root/pull/6258 fixes the type inference
problem (and therefore this test) for master.
> [DF] Fix test for ROOT-9674 (v6.22)

- root/dataframe/readShip.C
Column type is RVec<int>, not int, and RDF gets it wrong.
https://github.com/root-project/root/pull/6258 fixes the type inference
problem (and therefore this test) for master.
> [DF] Fix test for ROOT-9674 (v6.20)

- python/cpp/PyROOT_cpptests.py
Reported on mattermost that "import ROOT; ROOT.TGraphMultiErrors().SetLineColor(0)"
breaks with 6.22 and is now fixed in master due to the ROOT PR #6277.
> [PyROOT] Add test for using function decl

- scripts/custom_diff.py
The file mode 'U' (the universal newlines mode) is officialy
deprecated since python 3.4 (see https://docs.python.org/3.4/library/functions.html#open).
Fixes root-project/root#6480
> Fix deprecated file mode 'U'

- python/pytest/_pytest/assertion/rewrite.py
The issue was detected when running roottest with a conda ROOT
installation:
https://lcgapp-services.cern.ch/root-jenkins/view/conda/job/conda-nightlies/90/testReport/projectroot.python/pythonizations/roottest_python_pythonizations_pythonizations/
The fix corresponds to the following upstream pytest fix:
https://bitbucket.org/pytest-dev/pytest/commits/ce3f55c10452
> [Pytest] Backport 6.22: Fix incompatibility issue with Python>=3.8.4

- root/roofitstats/CMakeLists.txt
Standalone roottest doesn't handle transitive dependencies, so this
fixes it.
> [RF] Fix link dependencies.

- root/meta/tclass/execBrowseNonAccessibleType.ref
- root/treeformula/parse/PEvent.ref
The [PR #6752](https://github.com/root-project/root/pull/6752) introduce a warning message when trying to use a TBrowser in batch mode
> Adapt test to the changes of PR #6752

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
When testing the vectorised PDFs with ROOFIT_CHECK_CACHED_VALUES
defined, differences between batch and single-value computations
would be signalled only with cerr. This was converted to a proper
gtest failure with info messages etc.
Note that such a failure *may* be acceptable:
Defining ROOFIT_CHECK_CACHED_VALUES is a very strict checking mode
meant for debugging.
With only a single data point exceeding the tolerance the test will
fail. If the macro is not defined, tests only fail when *multiple*
points exceed the tolerance.
Please merge without my assistance.
> [RF] Convert cerr to gtest failure for testing vectorised PDFs.

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
- root/roofitstats/vectorisedPDFs/testGauss.cxx
This PR updates roottest so that the same-named PR in ROOT works correctly. It replaces the tests' roofit method calls to match the new interface. See the corresponding ROOT PR for more details.
> [RF] Purge old batch interface

- python/regression/PyROOT_regressiontests.py
Fixes https://github.com/root-project/root/issues/6915
Alternatively, the whole `roottest-python-regression-regression` test could be disabled in CMake if not building with opengl, but I prefer this option since `roottest-python-regression-regression` has many other tests that it would be interesting to run even if opengl is not there.
> [PyROOT][6915] Skip GL tests when unable to import GL classes

- python/cmdLineUtils/CMakeLists.txt
rootcp (unlike /bin/cp and as intended) is not copying the raw file but copy the content from the input to the output
It defaults to 'appending' mode rather than over-write/replace and thus if the file already exists (for example after
an interupted run of ctest) then the file use for the test contains more keys than expected.
This fixes https://github.com/root-project/root/issues/7054
> cmdLineUtils: survive the input being already created.

- root/multicore/executorTests.hxx
Both `htot` and `hred` have 10 bins, so including the bins for under- and overflow the maximum index to `GetBinContent` should be 11.
> Fix out-of-range access in executorTests

- cmake/modules/RoottestMacros.cmake
This should prevent the following kind of errors:
```
error MSB4018: The "Touch" task failed unexpectedly. [C:\Users\sftnight\build\roottest\ZERO_CHECK.vcxproj]
error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\Users\sftnight\build\roottest\Win32\RelWithDebInfo\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild'. [C:\Users\sftnight\build\roottest\ZERO_CHECK.vcxproj]
error MSB4018: File name: 'C:\Users\sftnight\build\roottest\Win32\RelWithDebInfo\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild' [C:\Users\sftnight\build\roottest\ZERO_CHECK.vcxproj]
error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\sftnight\build\roottest\ZERO_CHECK.vcxproj]
error MSB4018:    at System.IO.File.GetAttributes(String path) …
```
> Fix parallel building of tests on Windows

- root/meta/autoloading/headerParsingOnDemand/CMakeLists.txt
- root/meta/genreflex/noStreamer_noInputOperator/CMakeLists.txt
- root/tree/cloning/CMakeLists.txt
- use the proper `$<CONFIG>` value instead of `Release`
- disable several tests which are failing because of their PATH being too long (>260 characters) when running in Jenkins
> Fix several CI failures on Windows

- root/multicore/CMakeLists.txt
Even if TProcessExecutor is not used at runtime, TExecutor still
depends on the libMultiProc (what contains TProcessExecutor) at
link time.
This should fix a linking failure for this test in the conda builds (failure is [here](https://lcgapp-services.cern.ch/root-jenkins/job/conda-nightlies/313/testReport/junit/projectroot.root/multicore/roottest_root_multicore_tExecutorMT_build/)).
> [MultiProc] Fix library deps in tExecutorMT test

- root/multicore/tProcessExecutor.cpp
On MacOS, Cocoa spawns threads. That's very bad for TProcessExecutor's `fork`:
forking a multi-thread program can easily break, see e.g. `man 2 fork`.
Setting ROOT to batch mode works around the issue.
> [MultiProc] Set ROOT to batch mode before using TProcessExecutor

- root/meta/CMakeLists.txt
- root/multicore/CMakeLists.txt
The new spelling ensures transitive dependencies are brought in.
> Prefer ROOT::Lib to Lib when linking some tests

- root/multicore/tp_process_imt.cpp
Fixes the test after the changes in https://github.com/root-project/root/pull/7106
> Remove usage of deprecated SetMaxTasksPerFilePerWorker

- cmake/modules/RoottestMacros.cmake
- root/io/stdarray/CMakeLists.txt
- root/math/smatrix/CMakeLists.txt
- root/meta/genreflex/ROOT-5594/CMakeLists.txt
- root/meta/tclass/regression/CMakeLists.txt
- root/tree/fastcloning/CMakeLists.txt
Add `ACLiC.LinkLibs:  1` in the `.rootrc` files for Windows (thanks Philippe). According to [the documentation](https://github.com/root-project/root/blob/master/config/rootrc.in#L384-L390), this is already the default for the other platforms, while the default is `3` for Windows.
This allows to:
- enable several previously disabled tests
- remove several `WILL_FAIL` flags
- might allow to run in parallel without the `--repeat until-pass:3` flag
- re-run roottest several times in a row (should fix incremental and PR builds)
> Fix several issues with roottest on Windows

- cling/template/Singleton.h
This fixes the following error:
```
1134: IncrementalExecutor::executeFunction: symbol '?__type_info_root_node@@3U__type_info_node@@A' unresolved while linking [cling interface function]!
1134: You are probably missing the definition of struct __type_info_node __type_info_root_node
1134: Maybe you need to load the corresponding shared library?
```
> Use the proper __FUNCSIG__ macro on Windows

- .gitignore
It is a fairly common pattern to create a build directory directly
inside small repositories. Adding the directory to .gitignore helps
tools ignore its contents.
> Add /build to .gitignore

- python/distrdf/CMakeLists.txt
Sibling PR to https://github.com/root-project/root/pull/7416
> backport for v6.24: Build option for distributed RDF tests that use pyspark 

- root/roofitstats/vectorisedPDFs/testAddPdf.cxx
In the RooAddPdf class, a warning message was added recently for the
case where no normalization set was set. This commit silences that
warning by setting the normalization set with
`RooAddPdf::fixCoefNormalization`.
> [RF] Silence warnings in testAddPdf

- root/math/vecops/CMakeLists.txt
I found I needed to make this change to make the conda jenkins job build successfully.
> Add missing testRVecIO dependencies

- root/dataframe/test_nested_rvec_snapshot.C
On Windows it is not allowed to delete (or, in this case, "RECREATE")
a file while it is still open. We now enclose each Snapshot call in
its own scope so the file is closed before being recreated.
> [DF] Fix test_nested_rvec_snapshot on Windows

- CMakeLists.txt
This helps e.g. with https://github.com/root-project/root/issues/7081
as *if* roottest is configures with -DROOTSYS, that will be honored
instead of taking whatever the env var $ROOTSYS points to.
> Do not overwrite ROOTSYS if set from "outside":

- cling/dict/.rootrc
- cling/dict/ROOT-8739/.rootrc
- root/io/alloc/.rootrc
- root/io/datamodelevolution/misc/.rootrc
- root/io/double32/.rootrc
- root/io/emulated/.rootrc
- root/io/evolution/array/.rootrc
- root/io/perf/slowreading/.rootrc
- root/io/withoutDictionaries/.rootrc
- root/tree/selector/.rootrc
The ": 0" lines were added reasoning "we want no rootmaps" (but that doesn't mean we also need to disable explicit linking!)
The ": 2" lines were added to *force* rootmaps (but that doesn't mean we also need to disable explicit linking!)
https://github.com/root-project/root/pull/8017 needs this.
> Always link explicitly, even if we want (no) rootmap.

- CMakeLists.txt
- cmake/modules/RoottestMacros.cmake
- python/JupyROOT/CMakeLists.txt
- python/cmdLineUtils/CMakeLists.txt
The variable `PYTHON_EXECUTABLE_Development_Main` is only available when roottest is being built as a subdirectory within a ROOT build. Therefore, to let roottest work again in an independent build, we need to use `PYTHON_EXECUTABLE`, and rely on ROOT's exported version of Python to just find and use the same Python version in roottest.
Ideally, we should add in ROOT a call to `find_dependency` to match this call to `find_package(Python ...)` here, so that even this is not necessary in the future.
> Fix building roottest against already installed ROOT

- CMakeLists.txt
- cling/exception/CMakeLists.txt
- root/dataframe/CMakeLists.txt
where evolution/runforeign was looking for "foreign.ref" because ROOTBITS was unset.
> Some more Apple M1 roottest fixes

- root/tree/index/runindex64.C
As on M1, long double == double, doing the tree formula math in double
will not have sufficient precision to keep the least significant bits
around, causing the minor value not to be found back.
Instead, reduce the number such that a M1 `long double` can still represent
it. There is a new warning in TTreeIndex() that should be triggered by
providing the original value; the test should be extended to check for
said warning to be emitted on M1 in this case.
> On Apple M1, TTreeIndex cannot handle values that large:

- root/dataframe/test_snapshot_copyaddresses.C
Fix issue with files not being deleted on Windows due to file handles not yet released by the process
> Fix test_snapshot_copyaddresses.C on Windows

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h
Now that we require C++14 we can use the make_unique provided by the STL.
Companion PR for https://github.com/root-project/root/pull/8601 .
> Remove all usages of ROOT's std::make_unique backport

- root/math/smatrix/testInversion.cxx
This is to fix build errors with https://github.com/root-project/root/pull/8769. Preprocessor defines are dangerous.
> [math] Replace preprocessor define with constexpr in testInversion.cxx

- python/cpp/PointerPassing.C
This matches `array("L",...` and fixes a signedness mismatch on 32bit:
```
FAIL: Test passing of variants of void pointer arguments                
----------------------------------------------------------------------                                                              
Traceback (most recent call last):                                 
File "/home/sftnight/build/AXEL/src/roottest/python/cpp/PyROOT_cpptests.py", line 62, in test12VoidPointerPassing
self.assertEqual( addressofo.buffer_info()[0], Z.GimeAddressPtrPtr( addressofo ) )
AssertionError: 3079933240 != -1215034056   
```
FYI @wlav - I'd be interested to hear your opinion on this potential change to the code you wrote 14 years ago, if you find the time. I'm happy to hear that any time, also post-merge. This fixed a current …
> [py-cpp] Force address to be unsigned:

- root/dataframe/test_norootextension.cxx
Not only it's not needed, but it breaks standalone roottest builds.
> [DF] Remove useless include

- python/cpp/PyROOT_cpptests.py
Since array.array does not support int64b in Win64.
> [PyROOT] Protect test in case of Win64

- python/distrdf/test_include_headers.py
This prevents "headerX.hxx file not found" errors when both subtests try to concurrently clean the headers at cleanup time from different threads.
https://lcgapp-services.cern.ch/root-jenkins/job/root-nightly-master/LABEL=ROOT-ubuntu18.04,SPEC=nortcxxmod,V=master/2956/testReport/projectroot.roottest.python/distrdf/roottest_python_distrdf_spark_test_include_headers/
> [RDF] Serialize subtests of header distribution in DistRDF

- root/meta/CMakeLists.txt
- root/meta/clingTErrorDiagnostics.C
- root/meta/clingTErrorDiagnostics.ref
`TCling::ReportDiagnosticsToErrorHandler()` enables reporting cling diagnostics via the ROOT
error handler, as required by the experiments.
For more information, see the sibling PR: https://github.com/root-project/root/pull/8737.
> [tcling] Added test for `TCling::ReportDiagnosticsToErrorHandler()`

- boost/functional.hpp
- root/meta/CMakeLists.txt
- root/meta/execTypedefList.C
- root/meta/naming/cmsExample01.h
- root/meta/typelist_win32.v6.cxx17.txt
Fix errors due to the removal of `unary_function` and `binary_function` functions (deprecated in C++11, removed in C++17)
> Fix errors with std:c++17 on Windows

- CTestCustom.cmake
- root/rint/BackslashNewline_input.txt
- root/rint/CMakeLists.txt
Test that backslash-newline works in Rint (issue #8772).  See the complete discussion at https://github.com/root-project/root/pull/8772.
The matching PR for `root` was already merged.
> [Rint] Test for issue #8772 (backslash-newline not working in Rint)

- root/dataframe/CMakeLists.txt
With Visual Studio v16.3, test_readerarray fails in debug mode, so let's compile it in release mode. This is fixed with more recent versions of Visual Studio. This should fix the CI incremental builds
> Fix test_readerarray on Windows (debug)

- root/meta/tclass/CMakeLists.txt
ROOT PR #9244 apparently also fixes this test on MSVC; thus, removing the `WILLFAIL_ON_WIN32`.
Sibling PR here: https://github.com/root-project/root/pull/9244.
> [tcling] Remove `WILLFAIL_ON_WIN32` for roottest_root_meta_tclass_execSharedPtr

- root/meta/enumPayloadManipulation/CMakeLists.txt
Prevent the following error when ROOT has been built without PyROOT:
```
test 1416
Start 1416: roottest-root-meta-enumPayloadManipulation-checkEnumFwdDecl
1416: Test command: "C:\Program Files\CMake\bin\cmake.exe" "-DCMD=C:/Users/bellenot/AppData/Local/Continuum/miniconda3/python.exe^C:/Users/bellenot/git/roottest/root/meta/enumPayloadManipulation/checkEnumFwdDecl.py^--fixcling" "-DOUT=C:/Users/bellenot/build/x64/release/roottest/root/meta/enumPayloadManipulation/checkEnumFwdDecl.log" "-DOUTREF=C:/Users/bellenot/git/roottest/root/meta/enumPayloadManipulation/empty.ref" "-DERRREF=C:/Users/bellenot/git/roottest/root/meta/enumPayloadManipulation/empty.ref" "-DERR=C:/Users/bellenot/build/x64/release/roottest/root/meta/enumPayloadManipulation/checkEnumFwdDecl.err" …
```
> [skip-ci] Disable test if PyROOT is not available

- python/distrdf/test_definepersample.py
- python/distrdf/test_friend_trees.py
- python/distrdf/test_histo_write.py
- python/distrdf/test_include_headers.py
- python/distrdf/test_inv_mass.py
- python/distrdf/test_reducer_merge.py
Sibling PR to https://github.com/root-project/root/pull/9216 . Make sure we know how many cores the SparkContext is using in each test and thus adapt the distributed Snapshot test
> [DF] Specify cores of SparkContext in tests

- cmake/modules/SearchInstalledSoftwareRoottest.cmake
Following the recent changes in ROOT (commit #46f3742), the standalone roottest fails when building googletest:
```
roottest\googletest-prefix\src\googletest-build\CMakeFiles\CMakeTmp\testCCompiler.c : fatal error C1083: Cannot open include file: 'w32pragma.h': No such file or directory
```
This commit fixes the error. `w32pragma.h` and `sehmap.h` are not needed anyway
> [win] Remove forced includes w32pragma.h and sehmap.h

- root/meta/MakeProject/CMakeLists.txt
This resolves issues with in-tree builds of roottest where the build system would try to generate the dictionary before Hist is built and then fails because `TH1D.h` is included, but `Hist.pcm` not specified as a by-product.
Closes https://github.com/root-project/root/issues/9600
> stl_makeproject_test: Add dependency on Hist (if available)

- root/meta/tclass/execState.C
Use `gInterpreter->Declare()`, instead of `gROOT->ProcessLine()`, to introduce a forward declaration.  By design, `ProcessLine()` cannot guarantee that the user-provided code is not internally modified by cling.
See https://github.com/root-project/root/pull/9782.
> Minor fix to `meta/tclass/execState.C`

- python/distrdf/common/test_rungraphs.py
- python/distrdf/dask/test_rungraphs.py
- python/distrdf/spark/test_rungraphs.py
In roottest, python tests need to include a call to actually start the
test, unlike plain pytest tests that would just run without it.
When introducing distributed RunGraphs tests, this call was omitted,
effectively preventing CI tests of the feature.
> [DF] Actually run roottest distrdf tests of distributed RunGraphs

- scripts/Event.mk
in the old Makefile, many of the old variables are unset when running
from ctest. One of those is EXPLLINKLIBS. Instead, the dependent libraries
are linked through $^ - but only on Linux, not on macOS.
Fix roottest/root/treeformula/sync failing in Simple with
```
cling::DynamicLibraryManager::loadLibrary(): dlopen(/Users/sftnight/build/jenkins/night/LABEL/mac12/SPEC/soversion/V/master/roottest/root/treeformula/sync/libEvent.so, 0x0009): symbol not found in flat namespace '__ZN4TH1FC1EPKcS1_idd'
Processing Run.C(1)...
...
```
due to the missing dependent libraries (libHist).
That's fixed simply by using the default case for both Linux and macOS. Yay!
> Link libEvent against dependent libs:

- python/distrdf/CMakeLists.txt
- python/distrdf/test_friend_trees.py
- python/distrdf/test_histo_write.py
- python/distrdf/test_include_headers.py
- python/distrdf/test_inv_mass.py
- python/distrdf/test_reducer_merge.py
Logical backport of https://github.com/root-project/roottest/pull/817 but adjusted to the status of the tests in 6.24
> [6.24] Pyspark MacOs fork issue

- python/distrdf/dask/test_backend.py
- python/distrdf/spark/test_backend.py
Sibling PR of https://github.com/root-project/root/pull/9941 . Supersedes https://github.com/root-project/roottest/pull/825
> [DF] Remove tests of supported operations in distributed mode

- python/basic/Operators.C
Fix the following error on Windows 64 bit:
```
1299: Test implementation of operator bool ... ok
1299: Test converter operators of exact types ... ok
1299: Test converter operators of approximate types ... ERROR
1299: Templated method operator+/- ... ok
1299:
1299: ======================================================================
1299: ERROR: Test converter operators of approximate types
1299: ----------------------------------------------------------------------
1299: Traceback (most recent call last):
1299:   File "C:/Users/sftnight/git/roottest/python/basic/PyROOT_operatortests.py", line 127, in test2ApproximateTypes
1299:     o = OperatorUnsignedLong(); o.m_ulong = maxvalue + 128
1299: ValueError: can't convert negative value to unsigned long
1299:
1299: …
```
> [win64] fix python-basic-operator error on Windows 64 bit

- python/distrdf/CMakeLists.txt
Due to JIT relocation errors. Re-enable when fixed. Backport of #839
> [6.26] Disable distributed tests on M1 ARM

- python/cling/CMakeLists.txt
- root/tree/fastcloning/CMakeLists.txt
- root/tree/fastcloning/references/execCheckClusterRange_zlib_win64.ref
Disable the failing `roottest-python-cling-class` test and add a reference file for the `roottest-root-tree-fastcloning-execCheckClusterRange` test on Windows 64
> [win64] disable failing test and add a reference file

- python/pythonizations/CMakeLists.txt
On Windows 64, after removing the compiler flag workaround (PR #9829), the `pythonizations` test is failing like:
```
1386: -- TEST COMMAND --
1386: cd C:/Users/sftnight/build/release/roottest/python/pythonizations
1386: C:/Python38/python.exe C:/Users/sftnight/git/roottest/python/pythonizations/PyROOT_pythonizationtest.py --fixcling
1386: -- BEGIN TEST OUTPUT --
1386: ============================= test session starts =============================
1386: platform win32 -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
1386: rootdir: C:\Users\sftnight
1386: collected 7 items
1386:
1386: ..\..\..\..\..\git\roottest\python\pythonizations\PyROOT_pythonizationtest.py . [ 14%]
1386: .....Windows fatal exception: access violation
1386:
```
So temporary disable the test, until the underlying …
> [win64] Disable failing pythonizations test on Windows 64

- root/tree/cache/CMakeLists.txt
Remove the flag to always rebuild with Unix Makefiles to match what we do in `cling-stl-dicts`, which also has a library depending on a generated dictionary file (actually multiple). The reason this does not work is that `/fast` ignores dependencies, and in conjunction with `--always-make` it results in the build system not finding the generated files.
> Fix perfstattest-libevent-build on macOS

- root/meta/tclass/CMakeLists.txt
Backport of PR https://github.com/root-project/roottest/pull/791.
Sibling PR here: https://github.com/root-project/root/pull/10120.
> [tcling,v6-24] Remove `WILLFAIL_ON_WIN32` for roottest_root_meta_tclass_execSharedPtr

- cling/stl/dicts/CMakeLists.txt
- root/tree/cache/CMakeLists.txt
On macOS, ROOT now requires CMake 3.19 which gets us the `NEW` behavior of [CMP0113](https://cmake.org/cmake/help/latest/policy/CMP0113.html) aka "Makefile Generators do not repeat custom commands from target dependencies." This causes problems for `perfstattest-libevent-build` because the `build.make` file for `TheEvent` doesn't know how to build `G__TheEvent`. Manually list it as the targets to build, add `always-make` to `cling-stl-dicts-build` for consistency and a comment for when `CMP0113` makes problems in the future.
> Adapt for CMP0113

- cling/operator/EqualTest.ref-cling
- cling/operator/runEqualTest.C
- cling/template/separateDict/run.C
- cling/template/separateDict/sepDictLibs.ref
- cling/template/separateDict/sepDictLibs.ref32
- cling/template/separateDictNamespace/run.C
- cling/template/separateDictNamespace/run.good.output
- cling/template/separateDictNamespace/sepDictLibs.ref
- cling/template/separateDictNamespace/sepDictLibs.ref32
- cling/templateMembers/operatorEqual.ref
- cling/templateMembers/runoperatorEqual.C
- root/io/double32/longExample.h
To match https://github.com/root-project/root/pull/10350
* Update runEqualTest.C
* match verbosity
* match verbosity
* update output
* fix output
* fix output
* fix example
* fix hyphens
* fix hyphens
> [cling] fix `.Class` vs `.class` command

- root/multicore/CMakeLists.txt
- root/multicore/testTThreadedObjectAutoMemManagement.C
This causes failures with
```
#0  0xb6e5c7e3 in std::_Head_base<0u, std:🧵:id const&, false>::_M_head (__b=...) at /usr/include/c++/8/tuple:160
#1  0xb6e5c7cb in std::_Tuple_impl<0u, std:🧵:id const&>::_M_head (__t=...) at /usr/include/c++/8/tuple:351
#2  0xb6e5d488 in std::__get_helper<0u, std:🧵:id const&> (__t=...) at /usr/include/c++/8/tuple:1304
#3  0xb6e5d462 in std::get<0u, std:🧵:id const&> (__t=std::tuple containing = {...}) at /usr/include/c++/8/tuple:1315
#4  0xb6e5d4ad in std::pair<std:🧵:id const, unsigned int>::pair<std:🧵:id const&, 0u>(std::tuple<std:🧵:id const&>&, std::tuple<>&, std::_Index_tuple<0u>, std::_Index_tuple<>) (this=0xa48005e0, __tuple1=std::tuple containing = {...}, __tuple2=empty std::tuple) at /usr/include/c++/8/tuple:1667
#5  0xb6e5c863 in std::pair<std:🧵:id …
```
> testTThreadedObjectAutoMemManagement tries to return an int: let it.

- root/io/transient/base/CMakeLists.txt
Increase the timeout from 300 (5 min.) to 600 (10 min.). This should fix the following test failures on Window 64 bit:
```
04:01:26 	1519 - roottest-root-io-transient-base-WriteFile (Timeout)
04:01:26 	1520 - roottest-root-io-transient-base-hadd_autoload (Failed)
```
(`hadd_autoload` depends on `WriteFile`)
> Increase the timeout for root-io-transient-base-WriteFile

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h
- root/roofitstats/vectorisedPDFs/testGaussBinned.cxx
The retrieving of batches is an implementation detail of the RooFit batch mode that is already thoroughly testes by all the unit tests in the main ROOT repository that cover the batch mode (e.g. stressRooFit). It's not convenient to test this also in `roottest` because that makes it more cumbersome to change the interface.
> [RF] Avoid using RunContext in roottest

- root/tree/index/runindex64.C
As on M1, long double == double, doing the tree formula math in double
will not have sufficient precision to keep the least significant bits
around, causing the minor value not to be found back.
Instead, reduce the number such that a M1 `long double` can still represent
it. There is a new warning in TTreeIndex() that should be triggered by
providing the original value; the test should be extended to check for
said warning to be emitted on M1 in this case.
(cherry picked from commit f3c9780)
> On Apple M1, TTreeIndex cannot handle values that large [6.26]

- root/dataframe/test_snapshot.ref
This reverts commit e099f75e58dd039b8e3d35ce22ee5f389dd2900c.
We now keep the original ordering of the input branches in
Snapshot.
> [DF] Revert "[DF] Update test reference"

- python/distrdf/dask/check_backend.py
Test that C++ runtime_error is propagated correctly as a Python
RuntimeError with the original message from RDF. This is only needed in
Dask, Spark does not try to serialize the error instance.
More details at https://github.com/root-project/root/issues/11050
> [DF] Check C++ exception is correctly propagated in Dask 

- python/distrdf/common/CMakeLists.txt
- python/distrdf/dask/CMakeLists.txt
- python/distrdf/spark/CMakeLists.txt
Sibling PR of https://github.com/root-project/root/pull/11439
The distributed RDataFrame tutorials/tests have to create cluster objects, which take up resources on the machine. This is another step towards a clearer resource usage for both tutorials and tests. Whenever a cluster object is created, it now uses RESOURCE_LOCK test property to signal that no other cluster object should be created while the previous one is still running.
> Improvements on resource restrictions for distributed tests

- root/math/vdt/CMakeLists.txt
"too" is too general and may also match the build path. I could not find "too slow" being printed anywhere, so just check the output for "too inaccurate".
> Tighten FAILREGEX for stressVdt

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
`KahanSum` objects will no longer be implicitly converted to their underlying type after https://github.com/root-project/root/pull/11941. This commit explicitly converts them.
> remove KahanSum implicit conversion

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
KahanSum objects will no longer be implicitly converted to their underlying type after https://github.com/root-project/root/pull/11941. This commit explicitly converts them.
This PR (requested by @guitargeek) is the v6-28-00-patches version of https://github.com/root-project/roottest/pull/928.
> remove KahanSum implicit conversion - v6-28-00-patches PR

- root/dataframe/test_progressiveCSV.cxx
Replace deprecated call to `ROOT::RDF::MakeCsvDataFrame()` by `ROOT:RDF::FromCSV()`, as the former is deprecated and marked for removal in ROOT v6.30.
> [DF] Replace deprecated call to `ROOT::RDF::MakeCsvDataFrame()`

- root/io/TFile/assert_tcontext_thread_hoping.cxx
Add test that the thread local gDirectory and TContext are properly updated if another thread deletes a TFile there are pointing to.
Also attempt to test the race condition between the creation of the TContext and the gDirectory update (to reflect a deleted TFile). However it is quite rare (the window of miss behavior is small, i.e. within the TContext constructor).
See https://github.com/root-project/root/pull/11908
> Test gDirectory clean and TContext race condition

- root/meta/tclass/issue-6767/repro.ref
Backport of https://github.com/root-project/roottest/pull/935
> [v6-28] Adapt to new warning due to ROOT's #12173.

- requirements.txt
This helps us configure the new CI agents and is a nice way to document what's needed.
> Add requirements.txt for roottest Python requirements. [skip-ci]

- cling/functionTemplate/CMakeLists.txt
- python/CMakeLists.txt
- root/io/uniquePointer/rwconst.C
- root/roofitstats/CMakeLists.txt
Accidentally, I configured root without pyroot. This leads to a few test failures because of missing `if`s in roottest's cmake config.
> Fix roottest being configured without pyroot

- root/core/execStatusBitsCheck.C
- root/dataframe/test_ROOT9975.C
As of PR https://github.com/root-project/root/pull/12654, returning a non-`void` expression from `void`-returning function is only valid in an unnamed macro (in which case the diagnostic is filtered).
> [core][DF] Fix `-Wreturn-type` in tests

- root/collection/execMissing.C
- root/io/cpp11Containers/auxCode.h
Required to pass tests with newer versions of `libstdc++`.
> Custom allocator fixes

- root/io/newClassDef/current/template.h
- root/io/newClassDef/new/nstemplate.h
- root/io/newClassDef/new/template.h
C++20 made it invalid to use simple-template-ids for constructors and destructors: https://eel.is/c++draft/diff.cpp17.class#2
GCC 11 and later throw an error on this, with the unhelpful message `expected unqualified-id before '<some>' token`.
> Fix newClassDef tests with C++20

- root/meta/dictSelection/execAtlasTest2.C
Newer implementation have the members in the class itself rather than a base class
> dictSelection: ignore data members inside STL.

- root/meta/dictSelection/CMakeLists.txt
The [commit 5a601aacab4b3](https://github.com/root-project/roottest/commit/5a601aacab4b35bd7f90de71cc5b5e5769c400fc) fixes the execAtlasTest2 test on Windows (just remove the `WILL_FAIL` flag)
(cherry picked from commit 84f0a52f25dc510fcefe88d13f798dd398ad2cc0)
> Enable execAtlasTest2 on windows

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
- root/roofitstats/vectorisedPDFs/testAddPdf.cxx
- root/roofitstats/vectorisedPDFs/testArgusBG.cxx
- root/roofitstats/vectorisedPDFs/testBernstein.cxx
- root/roofitstats/vectorisedPDFs/testBifurGauss.cxx
- root/roofitstats/vectorisedPDFs/testBreitWigner.cxx
- root/roofitstats/vectorisedPDFs/testBukin.cxx
- root/roofitstats/vectorisedPDFs/testCBShape.cxx
- root/roofitstats/vectorisedPDFs/testChebychev.cxx
- root/roofitstats/vectorisedPDFs/testChiSquarePdf.cxx
- root/roofitstats/vectorisedPDFs/testCompatMode.cxx
- root/roofitstats/vectorisedPDFs/testDstD0BG.cxx
- root/roofitstats/vectorisedPDFs/testExponential.cxx
- root/roofitstats/vectorisedPDFs/testGamma.cxx
- root/roofitstats/vectorisedPDFs/testGauss.cxx
- root/roofitstats/vectorisedPDFs/testGaussBinned.cxx
- root/roofitstats/vectorisedPDFs/testJohnson.cxx
- root/roofitstats/vectorisedPDFs/testLandau.cxx
- root/roofitstats/vectorisedPDFs/testLegendre.cxx
- root/roofitstats/vectorisedPDFs/testLognormal.cxx
- root/roofitstats/vectorisedPDFs/testNestedPDFs.cxx
- root/roofitstats/vectorisedPDFs/testNovosibirsk.cxx
- root/roofitstats/vectorisedPDFs/testPoisson.cxx
- root/roofitstats/vectorisedPDFs/testPolynomial.cxx
- root/roofitstats/vectorisedPDFs/testProductPdf.cxx
- root/roofitstats/vectorisedPDFs/testVoigtian.cxx
This good practice to have the memory management handled automatically.
> [RF] Always use `addOwned()` overload that takes `unique_ptr`

- root/meta/race-12552/User.hpp
- root/meta/race-12552/User.xml
- root/meta/race-12552/exec_dlopenrace.C
To reduce the number of libraries unloaded on EL8 when clang++ (other platform don't seem to unload the dependent libraries) we preload some (but not all) of the libraries (keeping some to test the unloading and reloading of complex dictionary).
Also speed-up the test by stopping as soon as the lookups are done looping.
This is linked to https://github.com/root-project/root/pull/12863
> dlopen race: speed up when dependent library are also unloaded.

- python/stl/PyROOT_stltests.py
This should fix the test on fedora37 and fedora38, which complain
```
TypeError: argument of type 'int' is not iterable
```
after the recent upgrade to Python 3.11.3.
> Remove stray int in python/stl/PyROOT_stltests.py

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
Wrap return values of `RooAbsPdf::generate()` directly in unique pointers.
> [RF] Make `roottest` again compile in memory-safe RooFit mode

- python/distrdf/dask/check_reducer_merge.py
- python/distrdf/spark/check_reducer_merge.py
We only need to know that the event loop hasn't been triggered yet, the type of the proxy is an implementation detail.
> [skip-ci][DF] Remove unnecessary check for type of variable

- requirements.txt
Recent failures of roottest-python-JupyROOT-importROOT_notebook (specifically on Fedora 37) would report the message
```
[NbConvertApp] Converting notebook importROOT.ipynb to notebook
[NbConvertApp] Writing 988 bytes to importROOT_out.nbconvert.ipynb
...
File "/tmp/workspace/src/roottest/python/JupyROOT/nbdiff.py", line 68, in getFilteredLines
filteredLines = list(filter(customLineJunkFilter, open(fileName).readlines()))
^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'importROOT_out.ipynb'
```
This is due to a bug in nbconvert version 7.3, as described in https://github.com/jupyter/nbconvert/issues/1970. Other versions of the package do not suffer from the bug, so we update the requirements.txt file accordingly.
> [ci] Specify nbconvert version in requirements.txt

- cling/dict/enum/CMakeLists.txt
- cling/dict/enum/LinkDef.h
- cling/dict/enum/enum.h
- cling/dict/enum/execEnumDict.C
- cling/dict/enum/header.h
This is a heavily reduced case that shows the problem originally reported in https://github.com/cms-sw/cmssw/issues/42234.
> Add test for enum with two autoload annotations

- cling/dict/enum/CMakeLists.txt
- cling/dict/enum/LinkDef.h
- cling/dict/enum/enum.h
- cling/dict/enum/execEnumDict.C
- cling/dict/enum/header.h
This is a heavily reduced case that shows the problem originally reported in https://github.com/cms-sw/cmssw/issues/42234.
(cherry picked from commit 09f72c352068d7a2c2aad04a5ed8f4c9ad5b8e2c)
> [skip-ci] Add test for enum with two autoload annotations [v6.28]

- cling/dict/enum/CMakeLists.txt
- cling/dict/enum/LinkDef.h
- cling/dict/enum/enum.h
- cling/dict/enum/execEnumDict.C
- cling/dict/enum/header.h
This is a heavily reduced case that shows the problem originally reported in https://github.com/cms-sw/cmssw/issues/42234.
(cherry picked from commit 09f72c352068d7a2c2aad04a5ed8f4c9ad5b8e2c)
> [skip-ci] Add test for enum with two autoload annotations [v6.26]

- python/numba/PyROOT_numbatests.py
This will fix the test on macOS with LLVM 16 where interpreted code makes use of fma instructions that yield slightly different results.
> [PyROOT] Compare floating point numbers from numba with isclose

- CMakeLists.txt
Remove the `remove_definitions(${ROOT_DEFINITIONS})` hack, this has been fixed on the ROOT side and is not necessary anymore.
> [cmake][windows] Remove hack for Windows

- root/io/compression/MainEvent.cxx
libzstd-1.5.5-1.fc36.x86_64 increases size to 1162245
> Loosen test of compressed size in CompressionTest

- root/meta/rootmap/duplicateWarning/CMakeLists.txt
On this platform the copying of files does not work. For this reason, the test is disabled in order to keep the CI working in a healthy way.
> [Meta] Fix test on Windows by using the correct, platform independent way, of referring to the root command

- cmake/modules/RoottestMacros.cmake
- root/meta/ROOT-5694/CMakeLists.txt
This PR allows to group together tests and genreflex dictionary generation with fixtures. This new features allows to select group of tests with the "-R" comment of `ctest`.
This PR also fixes issue https://github.com/root-project/root/issues/7978.
> [CMake][ 7978] Lump together tests and genereflex dicts generation with fixtures

- root/meta/method/offset/testinterface.cpp
Use the proper `Longptr_t` instead of `Long_t` to cast pointers. This fixes the following warnings when compiling `testinterface.cxx` on Windows (x64):
```
Processing C:/ROOT-CI/src/roottest/root/meta/method/offset/execmethodtest.cxx+...
Info in <TWinNTSystem::ACLiC>: creating shared library C:/ROOT-CI/build/roottest/root/meta/method/offset/execmethodtest_cxx.dll
In file included from input_line_9:9:
In file included from C:/ROOT-CI/src/roottest/root/meta/method/offset/execmethodtest.cxx:3:
C:/ROOT-CI/src/roottest/root/meta/method/offset/testinterface.cpp:15:37: warning: cast to smaller integer type 'long' from 'const TestInterface *' [-Wpointer-to-int-cast]
Long_t checkTheRealOffsetDiff = ((Long_t)checkObjAsTestIface) - ((Long_t)checkObjAsTObj);
^~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> [windows] Fix warnings when compiling testinterface.cxx

- boost/functional.hpp
- root/meta/naming/cmsExample01.h
which has been removed in c++17
> [Cling] Fix CMS test relying on unary_function

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
- root/roofitstats/vectorisedPDFs/testGaussBinned.cxx
Sister PR of https://github.com/root-project/root/pull/12716.
> [RF] Adapt roottest to new `RooFit::EvalBackend()` command argument

- python/basic/PyROOT_operatortests.py
- python/numba/CMakeLists.txt
See https://docs.python.org/2/library/unittest.html#deprecated-aliases
> Use non-deprecated (and now removed) version of failUnlessEqual:

- python/stl/PyROOT_stltests.py
This should fix the test on fedora37 and fedora38, which complain
```
TypeError: argument of type 'int' is not iterable
```
after the recent upgrade to Python 3.11.3.
(cherry picked from commit aac224d8c3c3878637dfb3740b72e5754ad7aa60)
> Remove stray int in python/stl/PyROOT_stltests.py [v6.28]

- python/distrdf/common/CMakeLists.txt
- python/distrdf/dask/CMakeLists.txt
- python/distrdf/spark/CMakeLists.txt
The distributed RDataFrame test batteries use pytest to run all the tests together as a single ctest test. This is crucial to ensure only one mock cluster connection is open for all the needed tests. Sometimes, these test batteries may take much longer than expected. For example, on older and less powerful machines such as the ones running MacOS 11, running one distributed test battery usually takes 3 minutes, while it may take up to 10 minutes in case the node is overbooked and different process happen at the same time. Thus, this commit increases the timeout threshold to 20 minutes, in line with some of the longest running tests in our CI suite. This should ensure that scenarios with a very slow machine but no real test failure still work.
> [rdf] Increase timeout of distributed test batteries

- python/distrdf/common/CMakeLists.txt
- python/distrdf/dask/CMakeLists.txt
- python/distrdf/spark/CMakeLists.txt
The distributed RDataFrame test batteries use pytest to run all the tests together as a single ctest test. This is crucial to ensure only one mock cluster connection is open for all the needed tests. Sometimes, these test batteries may take much longer than expected. For example, on older and less powerful machines such as the ones running MacOS 11, running one distributed test battery usually takes 3 minutes, while it may take up to 10 minutes in case the node is overbooked and different process happen at the same time. Thus, this commit increases the timeout threshold to 20 minutes, in line with some of the longest running tests in our CI suite. This should ensure that scenarios with a very slow machine but no real test failure still work.
> [6.28] Backport of 1025

- python/regression/PyROOT_regressiontests.py
in presence of an overloaded operator().
This PR is relative to issue https://github.com/root-project/root/issues/13410 and the changes are a test for the fix which can be found in the root repository here https://github.com/root-project/root/pull/13820.
> [Cppyy][13410] Test accessibility of derived class

- root/core/assertHumanReadable.cxx
Sister PR of https://github.com/root-project/root/pull/13993.
> Adapt to removal of internal `TStringView`

- cling/reload/CMakeLists.txt
The underlying issue was solved with commit https://github.com/root-project/root/commit/afba1d737aeafd554ac4763fcc2d542de961be2a.
Thus, this PR re-enables this test.
> Closes JIRA issue ROOT-8245 (re-enable cling/reload/reloadvector test)

- requirements.txt
Currently `roottest-python-JupyROOT-tpython_notebook` fails on most platforms with the following difference to the reference output:
```diff
--- tpython.ipynb
+++ tpython_out.ipynb
@@ -16,7 +16,14 @@
"name": "stdout",
"output_type": "stream",
"text": [
-      "1\n"
+      "1"
+     ]
+    },
+    {
+     "name": "stdout",
+     "output_type": "stream",
+     "text": [
+      "\n"
]
}
],
```
The only exception is `alma8` which is stuck with `nbconvert-6.0.7` as newer versions require at least Python 3.7 or 3.8 in the most recent releases.
> [ci] Avoid nbconvert-7.14 for now

- root/dataframe/test_readTotemNtuple.ref
With ROOT7 enabled, The RDataFrame constructor taking (std::string_view
treename, std::string_view filename) now opens the file to check whether
the dataset is a TTree or an RNTuple. The warnings about the missing
dictionaries will now happen at construction time.
Create a new .ref file and instruct cmake to use the right one depending
on the ROOT configuration.
Sibling PR of https://github.com/root-project/root/pull/13090
> [DF] Update test with behaviour of new unified constructor

- root/tree/fastcloning/references/execCheckClusterRange.ref32
- root/tree/fastcloning/references/execCheckClusterRange_builtinzlib.ref
- root/tree/fastcloning/references/execCheckClusterRange_zlib.ref
In `root-project/root`, we are changing some of the TLeaf data member doc strings.
These class comments are part of the TStreamerInfo, which can affect compressed size as explaine by Philippe Canal in this comment: https://github.com/root-project/root/pull/14268#issuecomment-1865251700
Sister PR of [#14268](https://github.com/root-project/root/pull/14268).
> Update `tree-fastcloning-execCheckClusterRange` reference files

- requirements.txt
This is a BP of https://github.com/root-project/roottest/pull/1041
> [Backport][ci] Avoid nbconvert-7.14 for now

- root/io/compression/MainEvent.cxx
- root/tree/friend/testFriendsIndices.C
Since now the component is off by default.
Moreover, Proof was not tested, only headers included and not used.
> Remove traces of Proof

- python/numba/PyROOT_numbatests.py
- python/pythonizations/PyROOT_pythonizationtest.py
- python/regression/PyROOT_regressiontests.py
- python/ttree/PyROOT_ttreetests.py
This allows us to later deprecate it in the main ROOT repo without requiring another PR in roottest.
Also, explicit tests for the `TDirectory.__getattr__` are removed, because this is already covered by pythonization tests in the main repo:
* https://github.com/root-project/root/blob/master/bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py
* https://github.com/root-project/root/blob/master/bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py
> [PyROOT] Don't use the `TDirectory.__getattr__` pythonization

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h
- root/roofitstats/vectorisedPDFs/testAddPdf.cxx
- root/roofitstats/vectorisedPDFs/testArgusBG.cxx
- root/roofitstats/vectorisedPDFs/testBernstein.cxx
- root/roofitstats/vectorisedPDFs/testBifurGauss.cxx
- root/roofitstats/vectorisedPDFs/testBreitWigner.cxx
- root/roofitstats/vectorisedPDFs/testBukin.cxx
- root/roofitstats/vectorisedPDFs/testCBShape.cxx
- root/roofitstats/vectorisedPDFs/testChebychev.cxx
- root/roofitstats/vectorisedPDFs/testChiSquarePdf.cxx
- root/roofitstats/vectorisedPDFs/testCompatMode.cxx
- root/roofitstats/vectorisedPDFs/testDstD0BG.cxx
- root/roofitstats/vectorisedPDFs/testExponential.cxx
- root/roofitstats/vectorisedPDFs/testGamma.cxx
- root/roofitstats/vectorisedPDFs/testGauss.cxx
- root/roofitstats/vectorisedPDFs/testJohnson.cxx
- root/roofitstats/vectorisedPDFs/testLandau.cxx
- root/roofitstats/vectorisedPDFs/testLegendre.cxx
- root/roofitstats/vectorisedPDFs/testLognormal.cxx
- root/roofitstats/vectorisedPDFs/testNestedPDFs.cxx
- root/roofitstats/vectorisedPDFs/testNovosibirsk.cxx
- root/roofitstats/vectorisedPDFs/testPoisson.cxx
- root/roofitstats/vectorisedPDFs/testPolynomial.cxx
- root/roofitstats/vectorisedPDFs/testProductPdf.cxx
- root/roofitstats/vectorisedPDFs/testVoigtian.cxx
Reduce numer of events in the vectorised pdf tests, and accordingly increase the post-fit tolerance a bit, because the statistical fluctuations are higher.
This cuts down the total time of the tests on one CI node by about 14 minutes.
Furthermore, the vectorized evaluation is now validated so much - also in the full integration test `stressRooFit` - that these tests are mostly redundant.
> [RF] Reduce numer of events in the vectorised pdf tests

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h
- root/roofitstats/vectorisedPDFs/testAddPdf.cxx
- root/roofitstats/vectorisedPDFs/testArgusBG.cxx
- root/roofitstats/vectorisedPDFs/testBernstein.cxx
- root/roofitstats/vectorisedPDFs/testBifurGauss.cxx
- root/roofitstats/vectorisedPDFs/testBreitWigner.cxx
- root/roofitstats/vectorisedPDFs/testBukin.cxx
- root/roofitstats/vectorisedPDFs/testCBShape.cxx
- root/roofitstats/vectorisedPDFs/testChebychev.cxx
- root/roofitstats/vectorisedPDFs/testChiSquarePdf.cxx
- root/roofitstats/vectorisedPDFs/testCompatMode.cxx
- root/roofitstats/vectorisedPDFs/testDstD0BG.cxx
- root/roofitstats/vectorisedPDFs/testExponential.cxx
- root/roofitstats/vectorisedPDFs/testGamma.cxx
- root/roofitstats/vectorisedPDFs/testGauss.cxx
- root/roofitstats/vectorisedPDFs/testJohnson.cxx
- root/roofitstats/vectorisedPDFs/testLandau.cxx
- root/roofitstats/vectorisedPDFs/testLegendre.cxx
- root/roofitstats/vectorisedPDFs/testLognormal.cxx
- root/roofitstats/vectorisedPDFs/testNestedPDFs.cxx
- root/roofitstats/vectorisedPDFs/testNovosibirsk.cxx
- root/roofitstats/vectorisedPDFs/testPoisson.cxx
- root/roofitstats/vectorisedPDFs/testPolynomial.cxx
- root/roofitstats/vectorisedPDFs/testProductPdf.cxx
- root/roofitstats/vectorisedPDFs/testVoigtian.cxx
Reduce numer of events in the vectorised pdf tests, and accordingly increase the post-fit tolerance a bit, because the statistical fluctuations are higher.
This cuts down the total time of the tests on one CI node by about 14 minuits.
Furthermore, the vectorized evaluation is now validated so much - also in the full integration test `stressRooFit` - that these tests are mostly redundant.
Backport of: https://github.com/root-project/roottest/pull/1076
> [v628][RF] Reduce number of events in the vectorised pdf tests

- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.cxx
- root/roofitstats/vectorisedPDFs/VectorisedPDFTests.h
- root/roofitstats/vectorisedPDFs/testAddPdf.cxx
- root/roofitstats/vectorisedPDFs/testArgusBG.cxx
- root/roofitstats/vectorisedPDFs/testBernstein.cxx
- root/roofitstats/vectorisedPDFs/testBifurGauss.cxx
- root/roofitstats/vectorisedPDFs/testBreitWigner.cxx
- root/roofitstats/vectorisedPDFs/testBukin.cxx
- root/roofitstats/vectorisedPDFs/testCBShape.cxx
- root/roofitstats/vectorisedPDFs/testChebychev.cxx
- root/roofitstats/vectorisedPDFs/testChiSquarePdf.cxx
- root/roofitstats/vectorisedPDFs/testCompatMode.cxx
- root/roofitstats/vectorisedPDFs/testDstD0BG.cxx
- root/roofitstats/vectorisedPDFs/testExponential.cxx
- root/roofitstats/vectorisedPDFs/testGamma.cxx
- root/roofitstats/vectorisedPDFs/testGauss.cxx
- root/roofitstats/vectorisedPDFs/testJohnson.cxx
- root/roofitstats/vectorisedPDFs/testLandau.cxx
- root/roofitstats/vectorisedPDFs/testLegendre.cxx
- root/roofitstats/vectorisedPDFs/testLognormal.cxx
- root/roofitstats/vectorisedPDFs/testNestedPDFs.cxx
- root/roofitstats/vectorisedPDFs/testNovosibirsk.cxx
- root/roofitstats/vectorisedPDFs/testPoisson.cxx
- root/roofitstats/vectorisedPDFs/testPolynomial.cxx
- root/roofitstats/vectorisedPDFs/testProductPdf.cxx
- root/roofitstats/vectorisedPDFs/testVoigtian.cxx
Reduce numer of events in the vectorised pdf tests, and accordingly increase the post-fit tolerance a bit, because the statistical fluctuations are higher.
This cuts down the total time of the tests on one CI node by about 14 minuits.
Furthermore, the vectorized evaluation is now validated so much - also in the full integration test `stressRooFit` - that these tests are mostly redundant.
Backport of: https://github.com/root-project/roottest/pull/1076
> [v626][RF] Reduce number of events in the vectorised pdf tests

- root/io/issue-7754/mwe/read_updated.cxx
Fix the following error with `roottest-root-io-issue-7754-read_mwe_0` and `roottest-root-io-issue-7754-read_mwe_1` on Windows:
```
1702: Processing C:/root-dev/git/roottest/root/io/issue-7754/mwe/combined.cxx+(1)...
1702: Info in <TWinNTSystem::ACLiC>: creating shared library C:/root-dev/build/x64/debug/roottest/root/io/issue-7754/combined_cxx.dll
1702: In file included from input_line_9:6:
1702: In file included from C:/root-dev/git/roottest/root/io/issue-7754/mwe/combined.cxx:13:
1702: C:/root-dev/git/roottest/root/io/issue-7754/mwe/read_updated.cxx:27:5: error: member access into incomplete type 'TBranch'
1702:   br->GetEntry(0);
1702:     ^
1702: C:/root-dev/build/x64/debug/include/ROOT/TIOFeatures.hxx:17:7: note: forward declaration of 'TBranch'
1702: class TBranch;
1702:       ^
```
> [windows] Add missing include

- root/meta/tclass/regression/CMakeLists.txt
Compile the macro beforehand to prevent having to run the test twice,
the first time being always failing with the following error:
`LINK : fatal error LNK1561: entry point must be defined`
and successful the second time
> Fix failing execROOT_6277 on Windows

- python/basic/PyROOT_basictests.py
Template class instantiations are a bit fragile in PyROOT. At least the situation got better with ROOT 6.32. Buf for 6.30, we should not use templated classes to unit-test functionality that is not related to templates per se. In this concrete example, the
`test4ClassAndTypedefEquality` test was occasionally failing on some platforms (failures spotted on Fedora 38 and Ubuntu 23.10).
Also, using `cppyy` directly in only this test (instead of PyROOT) might have been a problem.
> Don't use templated class in `test4ClassAndTypedefEquality`

- root/meta/enums/CMakeLists.txt
- root/meta/enums/test_usingenum.cxx
- root/meta/enums/test_usingenum.ref
- root/multicore/exectsenums.C
This is testing https://github.com/root-project/root/issues/15406 and can test https://github.com/root-project/root/issues/15407 (be is currently disable as the issue is not fixed)
> Test TEnum::GetEnum with using statement.

- CMakeLists.txt
- cmake/modules/RoottestMacros.cmake
- python/JsMVA/CMakeLists.txt
- python/JupyROOT/CMakeLists.txt
- python/cmdLineUtils/CMakeLists.txt
- python/distrdf/backends/CMakeLists.txt
- python/numba/CMakeLists.txt
- root/meta/CMakeLists.txt
- root/rint/CMakeLists.txt
See:
https://cmake.org/cmake/help/latest/module/FindPythonInterp.html
Sister PR of https://github.com/root-project/root/pull/15420.
> [CMake] Replace deprecated `FindPythonInterp` module

- root/meta/enums/CMakeLists.txt
- root/meta/enums/test_usingenum.cxx
- root/meta/enums/test_usingenum.ref
- root/multicore/exectsenums.C
This was fixed by root-project/root#15408.
The failure on Windows was due to typeinfo(enum_type) returning a name
with the format enum enumname and until the addition (in that PR) of
the name normalization step, this was incorrectly handled by TEnum::GetEnumThis was fixed by root-project/root#15408.
The failure on Windows was due to typeinfo(enum_type) returning a name
with the format enum enumname and until the addition (in that PR) of
the name normalization step, this was incorrectly handled by TEnum::GetEnum
> execTEnumGetEnum now succeeds on Windows.

- CMakeLists.txt
- cmake/modules/RoottestMacros.cmake
- python/JsMVA/CMakeLists.txt
- python/JupyROOT/CMakeLists.txt
- python/cmdLineUtils/CMakeLists.txt
- python/distrdf/backends/CMakeLists.txt
- python/numba/CMakeLists.txt
- root/meta/CMakeLists.txt
- root/rint/CMakeLists.txt
See:
https://cmake.org/cmake/help/latest/module/FindPythonInterp.html
Backport of https://github.com/root-project/roottest/pull/1120
> [v632][CMake] Replace deprecated `FindPythonInterp` module

- root/ntuple/.rootrc
- root/ntuple/CMakeLists.txt
- root/ntuple/basics.C
- root/ntuple/test_basics.ref
Add the ntuple subfolder with a first, trivial test. Open the scope for RNTuple integration tests.
> [ntuple] add initial testing infrastructure

- python/basic/PyROOT_datatypetest.py
- python/regression/exec_root_6023.py
It is not a feature of cppyy, but only of our patches that cppyy can deal with `Long64_t` and the other basic ROOT typedefs.
In tests that have to do with these types, we should therefore use ROOT, so we don't rely on a patched cppyy and can move dealing with the ROOT types into our pythonizations.
Backport of https://github.com/root-project/roottest/pull/1129.
> [PyROOT] Use PyROOT and not just cppyy in tests dealing with ROOT types

- python/distrdf/backends/check_backend.py
- python/distrdf/backends/check_definepersample.py
To comply with reverting "[rdf] Restrict distributed initialization to executors only" in root repo: PR #15984.
> Revert "[df] Fix tests for distributed GetColumnNames"

- root/roofitstats/CMakeLists.txt
- root/roofitstats/vectorisedPDFs/testAddPdf.cxx
- root/roofitstats/vectorisedPDFs/testGauss.cxx
- root/roofitstats/vectorisedPDFs/testLandau.cxx
There should be no reason anymore for these tests not running on Windows.
> [RF] Don't exclude vectorized pdf tests on Windows

- python/numba/PyROOT_numbatests.py
This is to keep the test error style backward compatible with both numba <=0.59 and >=0.6 and prevent failures when enabling numpy 2.0
Fixes https://github.com/root-project/root/issues/16201
> [PyROOT] Update error style in numba derived class call

- python/numba/PyROOT_numbatests.py
This is to keep the test error style backward compatible with both numba <=0.59 and >=0.6 and prevent failures when enabling numpy 2.0
> [v632] [PyROOT] Update error style in numba derived class call

- cling/dict/runalgebra.C
which can generate warnings as unused and make the test fail in case the verbosity level of Aclic is increased.
> Fix wrong selection rules

- python/stl/CMakeLists.txt
Disable the `roottest-python-stl-stl` test for ROOT 6.26, 6.28, and 6.30, because it sporadically failed before the cppyy upgrade in ROOT 6.32.
> [PyROOT] Disable `roottest-python-stl-stl` because of sporadic failures

- python/numba/PyROOT_numbatests.py
The comparisons in execution times sometimes suffers a failure when the numba function is slower than pure python. This increases the number of loops to ensure the njit outperforms bare python.
> [PyROOT] Loop nJIT function more to prevent sporadic failures

- python/cling/PyClassTest2.C
- python/cling/PyClassTest4.C
Sister PR of https://github.com/root-project/root/pull/16175.
> [PyROOT] Migrate from `TPython::Eval()` to `TPython::Exec()`

- root/io/filemerger/CMakeLists.txt
On arm, a filesize comes out 27 bytes different from ~~x86~~ the 2019 arm values, so the tolerance had to be increased a bit.
This is a prerequisite for [#root-project/root-16526](https://github.com/root-project/root/pull/16526)
> [io] Increase a file size tolerance for arm builds.

- root/io/datamodelevolution/00/test2.cxx
the test fails to run otherwise (on debian12 - cling)
> [io] fix missing include in io-datamodelevolution-00-test2

- root/io/TFile/CMakeLists.txt
- root/io/webfile/CMakeLists.txt
Adapt roottests to geom being off. Related to [#16514](https://github.com/root-project/root/pull/16514)
> disable some geom-dependant tests when geom is OFF

- CMakeLists.txt
This should partially solve the issue with the rebuild (linking) of ROOT when building the tests.
See also: https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_TEST_ALL_DEPENDENCY.html
Requires CMake v3.29
> [cmake][win][skip-ci] Set the CMAKE_SKIP_TEST_ALL_DEPENDENCY variable

- root/ntuple/ntuple-makeproject/CMakeLists.txt
Sister PR https://github.com/root-project/root/pull/16964
> Disable roottest-root-ntuple-ntuple-makeproject-* on Linux+Clang

- root/io/hadd/CMakeLists.txt
- root/io/hadd/merge_changeComp_check_output.C
Verify that hadd behaves as intended for the 3 interesting cases regarding compression:
1. explicit compression given
2. no explicit compression given (default compression)
3. use first input's compression
Goes with https://github.com/root-project/root/pull/16949
> [hadd] add tests for RNTupleMerger compression

- python/distrdf/backends/check_variations.py
The resulting map of variations should only have the nominal key.
> [df] Add test with VariationsFor and no Vary

- root/meta/evolution/CMakeLists.txt
Due to failures of this test on all the platforms, I am disabling it for the next few hours. To be reverted once https://github.com/root-project/roottest/pull/1226 is merged (waiting for @pcanal).
> Temporarily disable mixedBase_merge1 test.

- .gitignore
- root/io/newstl/TestHelpers.C
- root/meta/evolution/mixedBase_merge1.ref
Companion PR of https://github.com/root-project/root/pull/16995
Instead of writing with the 'wrong' TStreamerInfo, the hadd of two file with conflicting StreamerInfo with the same version number write with the 'right' StreamerInfo ... but that StreamerInfo has missing fields with are now omitted in the writing.
The use case has 2 StreamerInfos:
(a)
v10 of ParticleImplVec
which inherits from v11 of Particle
which contains 3 floats
(b)
v10 (also) of ParticleImplVec
which inherits from v12 of Particle
which contains a float and moves the 3 pre-existing float into a base class (so they are 'missing' when using v11 of Particle).
The previous behavior of the hadd invocation was streaming
v10-a of ParticleImplVec
but ended up continuing the streaming with
v12 of Particle
Now the hadd invocation …
> Adapt to change in error case behavior.

- root/meta/naming/execCheckNaming_win32.ref
- root/meta/naming/execCheckNaming_win64.ref
correct default allocator is now recognized
Before, it didn't recognize it was a default allocator since it was confused by the class / const.
Sibling of https://github.com/root-project/root/pull/17048
> Update execCheckNaming in windows

- root/meta/MemberComments.ref
- root/meta/MemberComments_win32.ref
- root/meta/MemberComments_win64.ref
This PR updates the reference log for the [MemberComments](https://github.com/root-project/roottest/blob/master/root/meta/Makefile#L140-L141) test so that it reflects the changes proposed in https://github.com/root-project/root/pull/14077.
These changes include making public the enum `TH1::EInconsistencyBits`, and the addition of new public data members changes the output of [runMemberComments.C](https://github.com/root-project/roottest/blob/master/root/meta/runMemberComments.C#L34-L35), making the test fail.
> Update reference public members of TH1

- root/meta/MemberComments.ref
- root/meta/MemberComments_win32.ref
- root/meta/MemberComments_win64.ref
Sister PR of https://github.com/root-project/root/pull/17026.
> Update reference file to consider new Set*Color overloads

- python/distrdf/backends/check_backend.py
- python/distrdf/backends/check_cloned_actions.py
- python/distrdf/backends/check_definepersample.py
- python/distrdf/backends/check_distribute_cppcode.py
- python/distrdf/backends/check_distribute_headers_sharedlibs_files.py
- python/distrdf/backends/check_explicit_api.py
- python/distrdf/backends/check_friend_trees.py
- python/distrdf/backends/check_friend_trees_alignment.py
- python/distrdf/backends/check_histo_write.py
- python/distrdf/backends/check_inv_mass.py
- python/distrdf/backends/check_live_visualize.py
- python/distrdf/backends/check_reducer_merge.py
- python/distrdf/backends/check_rungraphs.py
- python/distrdf/backends/check_variations.py
- python/distrdf/backends/conftest.py
- python/distrdf/backends/test_all.py
And also add tests that still use explicit full names to distributed RDataFrame functions and classes, to check compatibility with previous usage.
Sibling PR of https://github.com/root-project/root/pull/16681
> [skip-ci] [df] Adapt to unified API (local and distributed)

- root/io/evolution/rules/execSourceTypes.cxx
- root/io/evolution/rules/execSourceTypes.ref
This is the companion PR to https://github.com/root-project/root/pull/17523
> io rules: test with array input followed by other inputs

- root/io/hadd/CMakeLists.txt
- root/tree/evolution/Makefile
* root/io/hadd: Correct the filename needing to be checked (shown as reading a non-existent file)
* root/tree/evolution: Add missing dependency (shown as reading a partial build library file)
The companion PR is https://github.com/root-project/root/pull/17700
> Fix issues seen in high parallel ctest run

- cling/dict/CMakeLists.txt
- cling/dict/runoperators.C
- cling/stl/default/CMakeLists.txt
- cling/stl/default/VectorSort.C
With gcc-15, the dereferencing and the + operator of iterators are marked nodiscard. This makes two tests fail, because the warning leads to a non-zero diff.
> Fix two test failures with functions marked nodiscard.

- root/dataframe/CMakeLists.txt
Necessary for Snapshot-related tests, now that snapshotting to RNTuple is being added (https://github.com/root-project/root/pull/15750).
> [DF] Add RNTuple as a possible dependency

- CMakeLists.txt
To be consistent with the main ROOT repository and to avoid this warning:
```txt
CMake Deprecation Warning at roottest/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
```
> [CMake] Raise minimum required CMake version to 3.20

- root/treeformula/string/execDrawString.C
This PR updates tree tutorials path within the ROOT library, according to https://github.com/root-project/root/pull/17097
> Update tree tutorials path

- root/treeformula/references/TreeFormulaReferencesGeneration.cxx
To avoid warnings such as
/Users/vpadulan/Programs/rootproject/roottest/root/treeformula/references/TreeFormulaReferencesGeneration.cxx:146:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
146 |   sprintf(fEventName,"Event%d_Run%d",ev,200);
|   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/_stdio.h:274:1: note: 'sprintf' has been explicitly marked deprecated here
274 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly …
> [treeformula] Avoid using deprecated sprintf

- .gitignore
Commit b1d0efe3bd "split stl and numerical conversions from main evolution-make"
> Update `.gitignore` after moved evolution tests

- root/io/bigevent/IoBigEventGeneration.cxx
The order of operations for fNevent was unspecified. Splitting the two expressions to make it well-defined.
> [io] Fix unsequenced operation in IoBigEventGeneration

- root/io/hadd/merge_changeComp_check_output.C
Companion of https://github.com/root-project/root/pull/18482
> [ntuple] RCluster/Pool moved out of Experimental

- root/io/TFile/execNestedCollectionStreamerInfo.cxx
default initialise a variable to avoid warnings in the test which cause it to fail on many Linux flavours.
```
roottest/root/io/TFile/execNestedCollectionStreamerInfo.cxx: In function ‘bool CheckNestedCollectionStreamerInfo(bool)’:
Warning: roottest/root/io/TFile/execNestedCollectionStreamerInfo.cxx:28:14: warning: ‘in.Inside::fValue’ may be used uninitialized [-Wmaybe-uninitialized]
28 |       Inside in;
|              ^~
```
@martamaja10
> 🚨  Remove compilation warning during ACLiC

- root/meta/rootcling/CMakeLists.txt
- root/meta/rootcling/streamerInfoStdFunction.h
- root/meta/rootcling/streamerInfoStdFunction.xml
Port of commit 9ff60071f40ed88086e527b78bd0fc807458c83a in root's master branch after the merge of the roottest repo into root's one.
The fix this tests is very important and it justifies the backport of the test.
Sibling PR https://github.com/root-project/root/pull/18840
> [636][test] Dictionary data member type contains a std::function

- root/meta/rootcling/CMakeLists.txt
- root/meta/rootcling/streamerInfoStdFunction.h
- root/meta/rootcling/streamerInfoStdFunction.xml
This reverts commit 134488dbb224e4cb2fb35447cfce299d297ccdcd.
> Revert "[test] Dictionary data member type contains a std::function"

- root/io/bigevent/CMakeLists.txt
It's not needed and it makes CMake fail to configure.
Backport of:
https://github.com/root-project/roottest/pull/1304
> [io] remove MathCore dependency from IoBigEventGeneration

- root/io/compression/MainEvent.cxx
libzstd-1.5.5-1.fc36.x86_64 increases size to 1162245
> Lose test of compressed size in CompressionTest
